//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by skyedit.rc
//
#define IDS_TT_CNAME                    1
#define IDS_TT_KEYWORDS                 2
#define ID_APPLY_BUTTON                 3
#define ID_CLEAR_BUTTON                 3
#define IDS_TT_DESCRIPTION              3
#define ID_DELETE_BUTTON                3
#define IDCANCEL2                       3
#define ID_CLEAR_FILTER                 3
#define IDS_TT_SCHOOL                   4
#define ID_ADD_BUTTON                   4
#define IDS_TT_EFFECTTYPE               5
#define ID_MOVEUP_BUTTON                5
#define ID_DELETE_BUTTON2               5
#define ID_MOVEDOWN_BUTTON              6
#define IDS_TT_TYPE                     6
#define IDD_ABOUTBOX                    100
#define IDD_SREDIT_FORM                 101
#define IDD_ERRORBAR                    103
#define IDC_POINTER_COPY                105
#define IDC_NODROP_CURSOR               106
#define IDR_MAINFRAME                   128
#define IDR_SREDITTYPE                  129
#define IDD_LOAD_DLG                    130
#define IDD_PROGRESS_DLG                131
#define IDR_RECORDTREE_MENU             132
#define IDB_FOLDER                      132
#define IDR_RECORDLIST_MENU             133
#define IDD_SRERROR_DLG                 133
#define IDB_FILE                        133
#define IDD_FILETREE_DLG                134
#define IDD_FINDBINARY_DLG              135
#define IDI_ARMOR                       136
#define IDD_SELECTRECORD_DLG            138
#define IDD_PROMPT_DLG                  139
#define IDR_DEFAULT_RECORD_ACCEL        140
#define IDD_UNDOBAR                     141
#define IDD_INPUT_DLG                   142
#define IDD_BATCHEDIT_DLG               143
#define IDD_FIND_DLG                    145
#define IDI_FIND                        145
#define IDR_MAINFRAME1                  146
#define IDR_SRVIEWTYPE                  146
#define IDR_LVLITEMLIST_MENU            150
#define IDR_LVLI_ACCELERATOR            151
#define IDR_EFFECTLIST_MENU             151
#define IDR_EFFECT_ACCELERATOR          152
#define IDR_BOOK_MENU                   156
#define IDR_SCRIPT_MENU                 157
#define IDD_RESOURCE_VIEW               176
#define IDD_KEYWORD_VIEW                181
#define IDD_WEAP_VIEW                   182
#define IDD_MGEF_VIEW                   183
#define IDD_FUNCTION_DLG                184
#define IDD_CONDITION_DLG               185
#define IDR_CONDITION_MENU              186
#define IDD_GLOB_VIEW                   186
#define IDD_GMST_VIEW                   187
#define IDR_COMPONENT_MENU              187
#define IDD_COBJ_VIEW                   188
#define IDR_COMPONENT_ACCEL             188
#define IDR_CONTAINERLIST_MENU          188
#define IDD_ENCH_VIEW                   189
#define IDR_LVLITEMLIST_MENU1           189
#define IDR_MGEFSOUNDLIST_MENU          189
#define IDD_SPEL_VIEW                   190
#define IDC_GOODDROP_CURSOR             190
#define IDD_AMMO_VIEW                   191
#define IDD_ARMO_VIEW                   192
#define IDD_BODYPARTS_DLG               193
#define IDD_ALCH_VIEW                   194
#define IDD_INGR_VIEW                   195
#define IDD_SCRL_VIEW                   196
#define IDD_BOOK_VIEW                   197
#define IDD_STAT_VIEW                   198
#define IDD_MISC_VIEW                   199
#define IDD_LVLI_VIEW                   201
#define IDD_LVLEDIT_DLG                 202
#define IDD_LVLN_VIEW                   203
#define IDD_LVSP_VIEW                   204
#define IDD_CONT_VIEW                   205
#define IDD_CONTITEMEDIT_DLG            206
#define IDD_LIGH_VIEW                   207
#define IDD_MGEFSNDDEDIT_DLG            208
#define IDD_ACTI_VIEW                   209
#define IDD_ARMA_VIEW                   210
#define IDD_SLGM_VIEW                   211
#define IDD_SHOU_VIEW                   212
#define IDD_WOOP_VIEW                   213
#define IDD_CLAS_VIEW                   214
#define IDD_RAWDATA_DLG                 215
#define IDD_PERK_VIEW                   216
#define IDD_CAMS_VIEW                   217
#define IDD_SOUN_VIEW                   218
#define IDD_BOUNDS_DLGDIALOG1           219
#define IDD_BOUNDS_DLG                  219
#define IDC_RECORDTREE                  1000
#define IDC_RESOURCE_TREE               1001
#define IDC_RECORDLIST                  1002
#define IDC_HBAR                        1003
#define IDC_VEDGE                       1004
#define IDC_FILENAME                    1005
#define IDC_FILE_LIST                   1006
#define IDC_FILESIZE                    1007
#define IDC_FILETIME                    1008
#define IDC_FILE_PROGRESS               1009
#define IDC_FILE_LABEL                  1010
#define IDC_PREVIEW_RICHEDIT            1011
#define IDC_FILE_PERCENT                1012
#define IDC_PREVIEW_IMAGE               1013
#define IDC_MESSAGE                     1014
#define IDC_DETAILS                     1015
#define IDC_TREECTRL                    1016
#define IDC_BINARYDATA_TEXT             1017
#define IDC_SETACTIVE                   1018
#define ID_SAVE_BUTTON                  1019
#define ID_CANCEL_BUTTON                1020
#define ID_UNCHECKALL_BUTTON            1022
#define ID_FIND_BUTTON                  1023
#define ID_CHECKALL_BUTTON              1025
#define IDC_PREVIOUS_TEXT               1027
#define IDC_CURRENT_TEXT                1029
#define ID_BUTTON1                      1030
#define IDC_FILTER_TEXT                 1030
#define ID_BUTTON2                      1032
#define IDC_PREVIOUS_FORMID             1033
#define ID_BUTTON3                      1035
#define IDC_CURRENT_FORMID              1036
#define IDC_LABEL                       1038
#define IDC_PARTS_LIST                  1043
#define IDC_INPUTTEXT                   1046
#define IDC_FIELD_LIST                  1048
#define IDC_BATCH_EDIT                  1050
#define IDC_FIND_LIST                   1052
#define IDC_EDITORID                    1053
#define IDC_SECTIONINDEX                1054
#define IDC_BINARY_CHECK                1055
#define IDC_SECTIONVALUE                1055
#define IDC_FORMID                      1056
#define IDC_SEARCH_COMBO                1057
#define IDC_CALCULATEALL                1058
#define IDC_LEVEL                       1059
#define IDC_CASESENSITIVE_CHECK         1060
#define IDC_CALCULATEEACH               1061
#define IDC_FORMID_CHECK                1061
#define IDC_USEALL                      1062
#define IDC_COUNT                       1062
#define IDC_FIND_LABEL                  1063
#define IDC_CHANCENONE                  1064
#define IDC_OBJECT_FORMID               1065
#define IDC_ITEM_LIST                   1066
#define IDC_FORMID2                     1068
#define IDC_WEIGHT                      1070
#define IDC_VALUE                       1073
#define IDC_UNKNOWN                     1074
#define IDC_FOV                         1074
#define IDC_RADIUS                      1075
#define IDC_FALLOFF                     1076
#define IDC_UNKNOWN2a                   1078
#define IDC_Y1                          1078
#define IDC_UNKNOWN3                    1079
#define IDC_Z1                          1079
#define IDC_ENCHANTCHARGE               1080
#define IDC_SECTION_ACTORVALUE          1080
#define IDC_Y2                          1080
#define IDC_NAME                        1081
#define IDC_CNAME                       1082
#define IDC_NNAME                       1082
#define IDC_RECHARGE1                   1082
#define IDC_Z2                          1082
#define IDC_NAME2                       1083
#define IDC_RECHARGE2                   1083
#define IDC_RECHARGE3                   1084
#define IDC_ENCHANTMENT                 1095
#define IDC_EQUIPSLOT                   1096
#define IDC_IMPACTSET                   1097
#define IDC_DRAWSOUND                   1099
#define IDC_SHEATHSOUND                 1100
#define IDC_SWINGSOUND                  1101
#define IDC_BOUNDSOUND                  1102
#define IDC_EDIT_ENCHANTMENT            1103
#define IDC_EDIT_EQUIPSLOT              1104
#define IDC_EDIT_IMPACTSET              1105
#define IDC_SOUND                       1106
#define IDC_EDIT_DRAWSOUND              1107
#define IDC_EDIT_SHEATHSOUND            1108
#define IDC_EDIT_SWINGSOUND             1109
#define IDC_EDIT_BOUNDSOUND             1110
#define IDC_TRAPSOUND                   1111
#define IDC_EDIT_TRAPSOUND              1112
#define IDC_MODEL                       1113
#define IDC_BASEWEAPON                  1114
#define IDC_DESTROYMODEL                1114
#define IDC_EDIT_BASEWEAPON             1115
#define IDC_FLICKERTYPE                 1118
#define IDC_REDSPIN                     1119
#define IDC_CREDITS                     1120
#define IDC_DAMAGE                      1120
#define IDC_GREENSPIN                   1120
#define IDC_BLUESPIN                    1121
#define IDC_KEYWORDS                    1124
#define IDC_ITEMNAME                    1125
#define IDC_DNAME                       1126
#define IDC_RESULTCOUNT                 1126
#define IDC_MAGNITUDE                   1126
#define IDC_TRANSLATION                 1126
#define IDC_SCHOOLLIST                  1127
#define IDC_COMPONENTCOUNT              1127
#define IDC_AREA                        1127
#define IDC_TYPELIST                    1128
#define IDC_CONDITION_LIST              1128
#define IDC_DURATION                    1128
#define IDC_REFERENCE_TEXT              1129
#define IDC_BASECOST                    1129
#define IDC_CHARGE                      1129
#define IDC_SELECTREFERENCE_BUTTON      1130
#define IDC_COST                        1130
#define IDC_EFFECTPLAYRATE              1130
#define IDC_REFERENCE_LABEL             1131
#define IDC_SKILLLEVEL                  1131
#define IDC_DESCRIPTION                 1131
#define IDC_STAFFMOD                    1131
#define IDC_QUESTITEM                   1132
#define IDC_FUNCTION_TEXT               1132
#define IDC_CASTTIME                    1132
#define IDC_SELECTENCHANT_BUTTON        1133
#define IDC_SELECTFUNCTION_BUTTON       1133
#define IDC_UNKNOWN2                    1133
#define IDC_SKILLBOOK                   1133
#define IDC_DYNAMIC                     1133
#define IDC_DANGEROUS                   1133
#define IDC_ADDKEYWORD_BUTTON           1134
#define IDC_FUNCTION_LABEL              1134
#define IDC_CARRIED                     1134
#define IDC_EDITKEYWORD_BUTTON          1135
#define IDC_PARAM1_TEXT                 1135
#define IDC_SPOTSHADOW                  1135
#define IDC_DELKEYWORD_BUTTON           1136
#define IDC_SELECTPARAM1_BUTTON         1136
#define IDC_UNKNOWNFLAG1                1136
#define IDC_CONDITION_BUTTON            1137
#define IDC_PARAM1_LABEL                1137
#define IDC_SELECTEQUIPSLOT_BUTTON      1137
#define IDC_NOTETYPE                    1137
#define IDC_UNKNOWNFLAG2                1137
#define IDC_PARAM2_TEXT                 1138
#define IDC_PLAYABLE                    1138
#define IDC_SPELLTOME                   1138
#define IDC_UNKNOWNFLAG3                1138
#define IDC_SELECT_IMPACTSET            1138
#define IDC_SECTION_CONDITIONS          1138
#define IDC_SELECTPARAM2_BUTTON         1139
#define IDC_SELECTPICKUPSOUND_BUTTON    1139
#define IDC_SELECTSOUND_BUTTON          1139
#define IDC_SELECT_STATICMODEL          1139
#define IDC_PARAM2_LABEL                1140
#define IDC_SELECTARMMODEL_BUTTON       1140
#define IDC_SELECTSTATICMODEL_BUTTON    1140
#define IDC_SELECT_DRAWSOUND            1140
#define IDC_VALUE_TEXT                  1141
#define IDC_SELECTUSESOUND_BUTTON       1141
#define IDC_SELECTSTATICMODEL_BUTTON2   1141
#define IDC_SELECTSPELL_BUTTON          1141
#define IDC_SELECT_SHEATHSOUND          1141
#define IDC_VALUE_LABEL                 1142
#define IDC_SELECT_SWINGSOUND           1142
#define IDC_SELECT_WATER                1142
#define IDC_OPERATOR_LIST               1143
#define IDC_SELECT_BOUNDSOUND           1143
#define IDC_OR_CHECK                    1144
#define IDC_SELECT_TRAPSOUND            1144
#define IDC_RUNTARGET_CHECK             1145
#define IDC_FUNCTION_LIST               1145
#define IDC_SELECT_BASEWEAPON           1145
#define IDC_USEGLOBAL_CHECK             1146
#define IDC_RESULTITEM                  1146
#define IDC_EDIT_RESULTITEM             1147
#define IDC_SELECTRESULTITEM_BUTTON     1148
#define IDC_COMPONENT_LIST              1149
#define IDC_PRKC_LIST                   1149
#define IDC_CRAFTSTATION                1150
#define IDC_TYPEFILTER_STATIC           1150
#define IDC_EDIT_CRAFTSTATION           1151
#define IDC_TYPEFILTER_LIST             1151
#define IDC_SELECTCRAFTSTATION_BUTTON   1152
#define IDC_HOSTILECHECK                1152
#define IDC_COMPONENT                   1153
#define IDC_RECOVERCHECK                1153
#define IDC_EDIT_COMPONENT              1154
#define IDC_DETRIMENTALCHECK            1154
#define IDC_BASEENCHANTMENT             1154
#define IDC_SELECTCOMPONENT_BUTTON      1155
#define IDC_PERCENTMAGCHECK             1155
#define IDC_EDIT_BASEENCHANT            1155
#define IDC_SELECTBASEENCHANT_BUTTON    1156
#define IDC_SELFONLYCHECK               1157
#define IDC_ITEMTYPES                   1157
#define IDC_FXPERSISTCHECK              1158
#define IDC_EDIT_ITEMTYPES              1158
#define IDC_BOUNDCHECK                  1159
#define IDC_SELECTITEMTYPES_BUTTON      1159
#define IDC_EFFECT_LIST                 1160
#define IDC_WARDCHECK                   1160
#define IDC_EFFECTNAME                  1161
#define IDC_UNKNOWNCHECK1               1161
#define IDC_EDIT_EFFECT                 1162
#define IDC_UNKNOWNCHECK2               1162
#define IDC_SELECTEFFECT_BUTTON         1163
#define IDC_UNKNOWNCHECK3               1163
#define IDC_PERK                        1164
#define IDC_EDIT_PERK                   1165
#define IDC_SELECTPERK_BUTTON           1166
#define IDC_UNKNOWNCHECK4               1166
#define IDC_SELECTEQUIPSLO_BUTTON       1167
#define IDC_UNKNOWNCHECK5               1167
#define IDC_SPELLFLAGS                  1168
#define IDC_UNKNOWNCHECK6               1168
#define IDC_SPELLTYPE                   1169
#define IDC_UNKNOWNCHECK7               1169
#define IDC_CASTTYPE                    1170
#define IDC_AUTOCALC                    1171
#define IDC_ACTORVALUE                  1171
#define IDC_CASTANIM                    1172
#define IDC_TYPEA                       1172
#define IDC_UNKNOWNCHECK8               1172
#define IDC_UNKNOWN1                    1173
#define IDC_TYPEB                       1173
#define IDC_DROPSOUND                   1173
#define IDC_TYPEC                       1174
#define IDC_RACE                        1174
#define IDC_UNKNOWN5                    1174
#define IDC_TYPED                       1175
#define IDC_SELECTDROPSOUND_BUTTON      1175
#define IDC_UNKNOWN6                    1175
#define IDC_IGNORERESIST                1176
#define IDC_SELECTRACE_BUTTON           1176
#define IDC_UNKNOWN7                    1176
#define IDC_VANISH                      1177
#define IDC_RATING                      1177
#define IDC_UNKNOWN8                    1177
#define IDC_PROJECTILE                  1178
#define IDC_ARMORTYPE                   1178
#define IDC_UNKNOWNFLAGS1               1178
#define IDC_ONEHAND                     1178
#define IDC_EDIT_PROJECTILE             1179
#define IDC_TEMPLATE                    1179
#define IDC_TWOHAND                     1179
#define IDC_SELECTPROJECTILE_BUTTON     1180
#define IDC_SELECTTEMPLATE_BUTTON       1180
#define IDC_TIME                        1180
#define IDC_UNKNOWN9                    1180
#define IDC_ALTERATION                  1180
#define IDC_SELECT_MODEL                1181
#define IDC_UNKNOWN10                   1181
#define IDC_BLOCK                       1181
#define IDC_PICKUPSOUND                 1182
#define IDC_UNKNOWN4                    1182
#define IDC_MATERIAL                    1183
#define IDC_STATICMODEL                 1183
#define IDC_DUALCAST                    1183
#define IDC_SELECT_DESTROYMODEL         1183
#define IDC_SMITHING                    1183
#define IDC_SELECTPICKUP_BUTTON         1184
#define IDC_SELECTMATERIAL_BUTTON       1184
#define IDC_USESOUND                    1184
#define IDC_SPELL                       1184
#define IDC_UNKNOWN10a                  1184
#define IDC_HEAVYARMOR                  1184
#define IDC_EDIT_DROPSOUND              1185
#define IDC_SELECT_DUALCAST             1185
#define IDC_UNKNOWN11                   1185
#define IDC_WATER                       1185
#define IDC_LIGHTARMOR                  1185
#define IDC_EDIT_PICKUPSOUND            1186
#define IDC_UNKNOWN12                   1186
#define IDC_PICKPOCKETING               1186
#define IDC_EDIT_RACE                   1187
#define IDC_EDIT_STATICMODEL            1187
#define IDC_EDIT_DUALCAST               1187
#define IDC_SNEAK                       1187
#define IDC_EDIT_TEMPLATE               1188
#define IDC_EDIT_USESOUND               1188
#define IDC_EDIT_SPELL                  1188
#define IDC_EXPLOSION                   1188
#define IDC_ALCHEMY                     1188
#define IDC_EDIT_MATERIAL               1189
#define IDC_SELECT_EXPLOSION            1189
#define IDC_EDIT_WATER                  1189
#define IDC_SPEECHCRAFT                 1189
#define IDC_FLICKER                     1190
#define IDC_IMPACTDATA                  1190
#define IDC_EDIT_EXPLOSION              1190
#define IDC_CONJURATION                 1190
#define IDC_EDIT_IMPACTDATA             1191
#define IDC_ART1                        1191
#define IDC_ILLUSION                    1191
#define IDC_SELECTIMPACTDATA_BUTTON     1192
#define IDC_SELECT_ART1                 1192
#define IDC_RESTORATION                 1192
#define IDC_FLICKERSLOW                 1193
#define IDC_BODYPARTS                   1193
#define IDC_EDIT_ART1                   1193
#define IDC_ENCHANTING                  1193
#define IDC_PULSE                       1194
#define IDC_ARMMODEL                    1194
#define IDC_POTIONTYPE                  1194
#define IDC_ART2                        1194
#define IDC_PULSESLOW                   1195
#define IDC_EDIT_ARMMODEL               1195
#define IDC_SKILL                       1195
#define IDC_SELECT_ART2                 1195
#define IDC_FLICKERNONE                 1196
#define IDC_SCALE                       1196
#define IDC_EDIT_ART2                   1196
#define IDC_SELECT_MATERIAL             1197
#define IDC_FADE                        1197
#define IDC_ART3                        1197
#define IDC_GLOBAL                      1198
#define IDC_RED                         1198
#define IDC_SELECT_ART3                 1198
#define IDC_EDIT_GLOBAL                 1199
#define IDC_GREEN                       1199
#define IDC_EDIT_ART3                   1199
#define IDC_SELECT_GLOBAL               1200
#define IDC_BLUE                        1200
#define IDC_ART4                        1200
#define IDC_OPENSOUND                   1201
#define IDC_COLOR                       1201
#define IDC_SELECT_ART4                 1201
#define IDC_EDIT_OPENSOUND              1202
#define IDC_EDIT_ART4                   1202
#define IDC_SELECT_OPENSOUND            1203
#define IDC_EDIT_SOUND                  1203
#define IDC_IMPACTSET1                  1203
#define IDC_CLOSESOUND                  1204
#define IDC_SELECT_IMPACTSET1           1204
#define IDC_EDIT_CLOSESOUND             1205
#define IDC_EDIT_IMPACTSET1             1205
#define IDC_SELECT_CLOSESOUND           1206
#define IDC_IMPACTSET2                  1206
#define IDC_TYPE                        1207
#define IDC_SELECT_IMPACTSET2           1207
#define IDC_EDIT_IMPACTSET2             1208
#define IDC_SHADER1                     1209
#define IDC_SELECT_SHADER1              1210
#define IDC_EDIT_SHADER1                1211
#define IDC_SHADER2                     1212
#define IDC_SELECT_SHADER2              1213
#define IDC_EDIT_SHADER2                1214
#define IDC_LIGHT                       1215
#define IDC_SELECT_LIGHT                1216
#define IDC_EDIT_LIGHT                  1217
#define IDC_SECONDSPELL                 1218
#define IDC_SELECT_SECONDSPELL          1219
#define IDC_EDIT_SECONDSPELL            1220
#define IDC_UNKNOWN13                   1221
#define IDC_SELECT_PROJECTILE           1222
#define IDC_UNKNOWN14                   1223
#define IDC_SELECT_PERK                 1224
#define IDC_UNKNOWN15                   1225
#define IDC_UNKNOWNCHECK9               1226
#define IDC_UNKNOWN16                   1226
#define IDC_NOAREACHECK                 1227
#define IDC_SOUND_LIST                  1228
#define IDC_ADDSOUND                    1229
#define IDC_DELETESOUND                 1230
#define IDC_TYPE_LIST                   1230
#define IDC_AMBIENTSOUND                1231
#define IDC_EDIT_AMBIENTSOUND           1232
#define IDC_SELECT_AMBIENTSOUND         1233
#define IDC_KEYWORD                     1234
#define IDC_EDIT_KEYWORD                1235
#define IDC_SELECT_KEYWORD              1236
#define IDC_VERB                        1237
#define IDC_RACE_LIST                   1238
#define IDC_ADD_RACELIST                1239
#define IDC_EDIT_RACELIST               1240
#define IDC_DEL_RACELIST                1241
#define IDC_FOOTSTEPS                   1242
#define IDC_EDIT_FOOTSTEPS              1243
#define IDC_SELECT_FOOTSTEPS            1244
#define IDC_MALETEXTURE                 1245
#define IDC_EDIT_MALETEXTURE            1246
#define IDC_SELECT_MALETEXTURE          1247
#define IDC_FEMALETEXTURE               1248
#define IDC_EDIT_FEMALETEXTURE          1249
#define IDC_SELECT_FEMALETEXTURE        1250
#define IDC_MALE1STTEXTURE              1251
#define IDC_EDIT_MALE1STTEXTURE         1252
#define IDC_SELECT_MALE1STTEXTURE       1253
#define IDC_FEMALE1STTEXTURE            1254
#define IDC_EDIT_FEMALE1STTEXTURE       1255
#define IDC_SELECT_FEMALE1STTEXTURE     1256
#define IDC_SELECT_RACE                 1257
#define IDC_MALEMODEL                   1258
#define IDC_SELECT_MALEMODEL            1259
#define IDC_FEMALEMODEL                 1260
#define IDC_FILLEDGEM                   1260
#define IDC_SELECT_FEMALEMODEL          1261
#define IDC_EDIT_FILLEDGEM              1261
#define IDC_MALE1STMODEL                1262
#define IDC_SELECT_FILLEDGEM            1262
#define IDC_SELECT_MALE1STMODEL         1263
#define IDC_CAPACITY                    1263
#define IDC_FEMALE1STMODEL              1264
#define IDC_CURRENTSOUL                 1264
#define IDC_POWERWORD1                  1264
#define IDC_SELECT_FEMALE1STMODEL       1265
#define IDC_EDIT_POWERWORD1             1265
#define IDC_SELECT_POWERWORD1           1266
#define IDC_SPELL1                      1267
#define IDC_TRAINERLEVEL                1267
#define IDC_EDIT_SPELL1                 1268
#define IDC_TRAINERSKILL                1268
#define IDC_SELECT_SPELL1               1269
#define IDC_MARKSMAN                    1269
#define IDC_POWERWORD2                  1270
#define IDC_LOCKPICKING                 1270
#define IDC_TEXTCONTROL                 1270
#define IDC_EDIT_POWERWORD2             1271
#define IDC_DESTRUCTION                 1271
#define IDC_VALUETEXT                   1271
#define IDC_SELECT_POWERWORD2           1272
#define IDC_NEXTPERK                    1272
#define IDC_SPELL2                      1273
#define IDC_EDIT_NEXTPERK               1273
#define IDC_EDIT_SPELL2                 1274
#define IDC_SELECT_NEXTPERK             1274
#define IDC_SELECT_SPELL2               1275
#define IDC_PERKDATA_LIST               1275
#define IDC_POWERWORD3                  1276
#define ID_DELETEPERK_BUTTON            1276
#define IDC_EDIT_POWERWORD3             1277
#define ID_ADDPERK_BUTTON               1277
#define IDC_SELECT_POWERWORD3           1278
#define IDC_SECTIONTYPE                 1278
#define IDC_SPELL3                      1279
#define IDC_SECTION_EDITORID            1279
#define IDC_EDIT_SPELL3                 1280
#define IDC_EDIT_SECTIONEDITORID        1280
#define IDC_SELECT_SPELL3               1281
#define IDC_SELECT_SECTIONEDITORID      1281
#define IDC_SECTION_VALUELABEL1         1282
#define IDC_SECTIONEFFECTTYPE           1283
#define IDC_SECTIONAPPLYTYPE            1284
#define IDC_SECTIONUNKNOWNTYPE          1285
#define IDC_SECTION_EDITORIDLABEL       1286
#define IDC_PRKC_LABEL                  1287
#define IDC_RICHEDIT21                  1288
#define IDC_ACTIVECHECK                 1289
#define IDC_FILTERTEXT                  1290
#define IDC_IMAGESPACE                  1291
#define IDC_EDIT_IMAGESPACE             1292
#define IDC_SELECT_IMAGESPACE           1293
#define IDC_X1                          1294
#define IDC_X2                          1295
#define IDC_UNKNOWN3a                   1296
#define IDC_SOUNDFILE                   1297
#define IDC_SELECT_SOUNDFILE            1298
#define IDC_SOUNDREF                    1299
#define IDC_EDIT_SOUNDREF               1300
#define IDC_SELECT_SOUNDREF             1301
#define IDC_BOUNDS                      1302
#define IDS_TT_EDITORID                 15000
#define IDS_TT_FULLNAME                 15001
#define IDS_TT_FORMID                   15002
#define IDS_TT_ARMORTYPE                15003
#define IDS_TT_ARMOR                    15004
#define IDS_TT_VALUE                    15005
#define IDS_TT_WEIGHT                   15006
#define IDS_TT_HEALTH                   15007
#define IDS_TT_ENCHANTMENT              15008
#define IDS_TT_SCRIPT                   15009
#define IDS_TT_PLAYABLE                 15010
#define IDS_TT_HIDERINGS                15011
#define IDS_TT_HIDEAMULET               15012
#define IDS_TT_MALEICON                 15013
#define IDS_TT_FEMALEICON               15014
#define IDS_TT_BIPED                    15015
#define IDS_TT_QUESTITEM                15016
#define IDS_TT_MODEL                    15017
#define IDS_TT_MALEWORLDMODEL           15018
#define IDS_TT_FEMALEWORLDMODEL         15019
#define IDS_TT_MALEBIPEDMODEL           15020
#define IDS_TT_FEMALEBIPEDMODEL         15021
#define IDS_TT_SAVE                     15022
#define IDS_TT_APPLY                    15023
#define IDS_TT_CANCEL                   15024
#define IDS_TT_EDITBIPED                15025
#define IDS_TT_EDITSCRIPT               15026
#define IDS_TT_SELECTSCRIPT             15027
#define IDS_TT_EDITENCHANT              15028
#define IDS_TT_SELECTENCHANT            15029
#define IDS_TT_SOUND                    15030
#define IDS_TT_DANGEROUS                15031
#define IDS_TT_FOODITEM                 15032
#define IDS_TT_AUTOCALC                 15033
#define IDS_TT_DAMAGE                   15034
#define IDS_TT_SPEED                    15035
#define IDS_TT_ENCHANTPOINTS            15036
#define IDS_TT_IGNORERESIST             15037
#define IDS_TT_QUALITY                  15038
#define IDS_TT_APPATYPE                 15039
#define IDS_TT_SCROLL                   15040
#define IDS_TT_NOTAKE                   15041
#define IDS_TT_TEACHES                  15042
#define IDS_TT_CONTRESPAWNS             15043
#define IDS_TT_OPENSOUND                15044
#define IDS_TT_CLOSESOUND               15045
#define IDS_TT_ENCHTYPE                 15046
#define IDS_TT_COST                     15047
#define IDS_TT_CHARGE                   15048
#define IDS_TT_INGREDIENT               15049
#define IDS_TT_SPRING                   15050
#define IDS_TT_SUMMER                   15051
#define IDS_TT_FALL                     15052
#define IDS_TT_WINTER                   15053
#define IDS_TT_CALCEACH                 15054
#define IDS_TT_CALCALL                  15055
#define IDS_TT_CHANCENONE               15056
#define IDS_TT_CREATURETEMPLATE         15057
#define IDS_TT_USEALLSPELLS             15058
#define IDS_TT_SCPTTYPE                 15059
#define IDS_TT_USES                     15060
#define IDS_TT_CAPACITY                 15061
#define IDS_TT_SOUL                     15062
#define IDS_TT_SOUNDFILE                15063
#define IDS_TT_MINATTENUATION           15064
#define IDS_TT_MAXATTENUATION           15065
#define IDS_TT_STATICATTENUATION        15066
#define IDS_TT_FREQADJUSTMENT           15067
#define IDS_TT_STARTTIME                15068
#define IDS_TT_STOPTIME                 15069
#define IDS_TT_RANDOMFREQSHIFT          15070
#define IDS_TT_RANDOMPLAY               15071
#define IDS_TT_RANDOMLOCATION           15072
#define IDS_TT_LOOP                     15073
#define IDS_TT_MENUSOUND                15074
#define IDS_TT_IGNOREENVIRONMENT        15075
#define IDS_TT_2DSOUND                  15076
#define IDS_TT_360LFE                   15077
#define IDS_TT_SPELTYPE                 15078
#define IDS_TT_LEVEL                    15079
#define IDS_TT_IGNORELOS                15080
#define IDS_TT_NOABSORBREFLECT          15081
#define IDS_TT_PCSTARTSPELL             15082
#define IDS_TT_SCRIPTALWAYSAPPLIES      15083
#define IDS_TT_SILENCEIMMUNE            15084
#define IDS_TT_WEAPTYPE                 15085
#define IDS_TT_REACH                    15086
#define IDS_TT_ICON                     15087
#define IDS_TT_SELECTCREATURE           15088
#define IDS_TT_EDITCREATURE             15089
#define IDS_TT_EDITSOUND                15090
#define IDS_TT_SELECTSOUND              15091
#define IDS_TT_EDITINGREDIENT           15092
#define IDS_TT_SELECTINGREDIENT         15093
#define IDS_TT_FADE                     15094
#define IDS_TT_REDCOLOR                 15095
#define IDS_TT_GREENCOLOR               15096
#define IDS_TT_BLUECOLOR                15097
#define IDS_TT_TIME                     15098
#define IDS_TT_OFFBYDEFAULT             15099
#define IDS_TT_FLICKER                  15100
#define IDS_TT_SPOTLIGHT                15101
#define IDS_TT_SPOTSHADOW               15102
#define IDS_TT_DYNAMIC                  15103
#define IDS_TT_NEGATIVE                 15104
#define IDS_TT_COLORBOX                 15105
#define IDS_TT_CARRIED                  15106
#define IDS_TT_FLICKERTYPE              15107
#define IDS_TT_FOV                      15108
#define IDS_TT_FALLOFF                  15109
#define IDS_TT_RADIUS                   15110
#define ID_FILE_IMPORT_CSV              32772
#define ID_FILE_EXPORT_SELECTEDITEMS    32773
#define ID_FILE_EXPORTCSV_SELECTEDITEMS 32774
#define ID_FILE_EXPORTCSV_ALLITEMS      32775
#define ID_FILE_EXPORTCSV_ITEMTYPE      32776
#define ID_FILE_EXPORTCSV_SELECTEDITEMS2 32776
#define ID_RECORDTREE_RELOAD            32777
#define ID_RECORDTREE_EXPORTTOCSV       32778
#define ID_VIEW_FILESTRUCTURE           32779
#define ID_FILE_EXPORT_CSVEXTERIORLOCATIONS 32780
#define ID_FILE_EXPORT_CSVEXTMAPMARKERS 32781
#define ID_HELP_TESTFIELDLOOKUP         32782
#define ID_FILE_EXPORT_CSVEXPORTEXTERIORPLANTS 32783
#define ID_EDIT_FINDBINARYDATA          32784
#define ID_HELP_TESTFINDFORMID          32785
#define ID_EDIT_SELECTALL               32786
#define ID_VIEW_ERROR_BAR               32787
#define ID_TEST_MEMORYSPEED             32788
#define ID_TEST_TOKENSCRIPTS            32789
#define ID_MENU_CLEAN                   32790
#define ID_RECORD_CLEAN                 32791
#define ID_RECORD_MOVEACTIVE            32792
#define ID_MENU_EDITRECORD              32794
#define ID_MENU_NEWRECORD               32795
#define ID_EDIT_NEWRECORD               32796
#define ID_RECORD_TOGGLEDELETE          32797
#define ID_MENU_TOGGLEIGNORE            32798
#define ID_RECORD_TOGGLEIGNORE          32800
#define ID_MENU_TOGGLEQUEST             32801
#define ID_RECORD_TOGGLEQUEST           32802
#define ID_VIEW_UNDOBAR                 32803
#define ID_RECORD_RENAME                32804
#define ID_RECORD_CREATECOPY            32805
#define ID_RECORD_BATCHEDIT             32806
#define ID_LVLOLIST_DELETE              32807
#define ID_LVLLIST_DELETE               32808
#define ID_LVLLIST_ADD                  32809
#define ID_LVLLIST_EDIT                 32810
#define ID_DELETE_ITEM                  -32724
#define ID_ADD_COUNT                    32813
#define ID_MINUS_COUNT                  32814
#define ID_ADD_LEVEL                    32815
#define ID_MINUS_LEVEL                  32816
#define ID_LVL_EDITRECORD               32818
#define ID_LVLLIST_EDITRECORD           32819
#define ID_EFFECTLIST_EDIT              32820
#define ID_EFFECTLIST_ADD               32821
#define ID_EFFECTLIST_DELETE            32822
#define ID_EFFECTLIST_EDITSCRIPT        32824
#define ID_HELP_TESTOUTPUTEFFECTS       32825
#define ID_VIEW_RESOURCEVIEWER          32828
#define ID_HELP_TESTRECORDSIZE          32829
#define ID_HELP_UESPWIKI                32831
#define ID_HELP_CSWIKI                  32832
#define ID_TEST_CLEANRECOMPILEALL       32834
#define ID_TEST_RECOMPILEALL            32835
#define ID_HELP_TESTCOMPARESCRIPTS      32836
#define ID_VIEW_RESETLISTS              32837
#define ID_ROOT_INSERTBEFORE            32838
#define ID_ROOT_INSERTAFTER             32839
#define ID_ROOT_MOVEUP                  32840
#define ID_ROOT_MOVEDOWN                32841
#define ID_ROOT_DELETE                  32842
#define ID_COND_INSERTBEFORE            32843
#define ID_COND_INSERTAFTER             32844
#define ID_COND_MOVEUP                  32845
#define ID_COND_MOVEDOWN                32846
#define ID_COND_DELETE                  32847
#define ID_CONDITION_COPYCONDITON       32848
#define ID_COND_COPYCONDITON            32849
#define ID_COND_COPYCONDITION           32850
#define ID_COMPONENT_ADD                32851
#define ID_COMPONENT_DELETE             32852
#define ID_COMPONENT_EDIT               32853
#define ID_Menu                         32854
#define ID_COMPONENT_INCREASE           32855
#define ID_COMPONENT_DECREASE           32856
#define ID_SNDDLIST_DELETE              32861
#define ID_SNDDLIST_EDIT                32862
#define ID_SNDDLIST_ADD                 32863
#define ID_SNDDLIST_EDITRECORD          32864
#define ID_MENU_VIEWDATADATA            32865
#define ID_MENU_VIEWRAWDATA             32866
#define ID_HELP_TESTOUTPUTPERKS         32867
#define ID_EDIT_USELOCALSTRINGS         32868
#define ID_EDIT_SETMODAUTHOR            32869
#define ID_EDIT_SETMODDESCRIPTION       32870

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         32871
#define _APS_NEXT_CONTROL_VALUE         1304
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
