//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by skyedit.rc
//
#define IDS_TT_CNAME                    1
#define IDS_TT_KEYWORDS                 2
#define ID_APPLY_BUTTON                 3
#define ID_CLEAR_BUTTON                 3
#define IDS_TT_DESCRIPTION              3
#define ID_DELETE_BUTTON                3
#define IDCANCEL2                       3
#define ID_CLEAR_FILTER                 3
#define IDS_TT_SCHOOL                   4
#define ID_ADD_BUTTON                   4
#define IDS_TT_EFFECTTYPE               5
#define ID_MOVEUP_BUTTON                5
#define ID_DELETE_BUTTON2               5
#define ID_MOVEDOWN_BUTTON              6
#define IDS_TT_TYPE                     6
#define IDD_ABOUTBOX                    100
#define IDD_SREDIT_FORM                 101
#define IDD_ERRORBAR                    103
#define IDR_MAINFRAME                   128
#define IDR_SREDITTYPE                  129
#define IDD_LOAD_DLG                    130
#define IDD_PROGRESS_DLG                131
#define IDR_RECORDTREE_MENU             132
#define IDB_FOLDER                      132
#define IDR_RECORDLIST_MENU             133
#define IDD_SRERROR_DLG                 133
#define IDB_FILE                        133
#define IDD_FILETREE_DLG                134
#define IDD_FINDBINARY_DLG              135
#define IDI_ARMOR                       136
#define IDD_SELECTRECORD_DLG            138
#define IDD_PROMPT_DLG                  139
#define IDR_DEFAULT_RECORD_ACCEL        140
#define IDD_UNDOBAR                     141
#define IDD_INPUT_DLG                   142
#define IDD_BATCHEDIT_DLG               143
#define IDD_FIND_DLG                    145
#define IDI_FIND                        145
#define IDR_MAINFRAME1                  146
#define IDR_SRVIEWTYPE                  146
#define IDR_LVLITEMLIST_MENU            150
#define IDR_LVLI_ACCELERATOR            151
#define IDR_EFFECTLIST_MENU             151
#define IDR_EFFECT_ACCELERATOR          152
#define IDR_BOOK_MENU                   156
#define IDR_SCRIPT_MENU                 157
#define IDD_RESOURCE_VIEW               176
#define IDD_KEYWORD_VIEW                181
#define IDD_WEAP_VIEW                   182
#define IDD_MGEF_VIEW                   183
#define IDD_FUNCTION_DLG                184
#define IDD_CONDITION_DLG               185
#define IDR_CONDITION_MENU              186
#define IDD_GLOB_VIEW                   186
#define IDD_GMST_VIEW                   187
#define IDR_COMPONENT_MENU              187
#define IDD_COBJ_VIEW                   188
#define IDR_COMPONENT_ACCEL             188
#define IDD_ENCH_VIEW                   189
#define IDC_RECORDTREE                  1000
#define IDC_RESOURCE_TREE               1001
#define IDC_RECORDLIST                  1002
#define IDC_HBAR                        1003
#define IDC_VEDGE                       1004
#define IDC_FILENAME                    1005
#define IDC_FILE_LIST                   1006
#define IDC_FILESIZE                    1007
#define IDC_FILETIME                    1008
#define IDC_FILE_PROGRESS               1009
#define IDC_FILE_LABEL                  1010
#define IDC_PREVIEW_RICHEDIT            1011
#define IDC_FILE_PERCENT                1012
#define IDC_PREVIEW_IMAGE               1013
#define IDC_MESSAGE                     1014
#define IDC_DETAILS                     1015
#define IDC_TREECTRL                    1016
#define IDC_BINARYDATA_TEXT             1017
#define IDC_SETACTIVE                   1018
#define ID_SAVE_BUTTON                  1019
#define ID_CANCEL_BUTTON                1020
#define ID_UNCHECKALL_BUTTON            1022
#define ID_FIND_BUTTON                  1023
#define ID_CHECKALL_BUTTON              1025
#define IDC_PREVIOUS_TEXT               1027
#define IDC_CURRENT_TEXT                1029
#define ID_BUTTON1                      1030
#define IDC_FILTER_TEXT                 1030
#define ID_BUTTON2                      1032
#define IDC_PREVIOUS_FORMID             1033
#define ID_BUTTON3                      1035
#define IDC_CURRENT_FORMID              1036
#define IDC_LABEL                       1038
#define IDC_INPUTTEXT                   1046
#define IDC_FIELD_LIST                  1048
#define IDC_BATCH_EDIT                  1050
#define IDC_FIND_LIST                   1052
#define IDC_EDITORID                    1053
#define IDC_BINARY_CHECK                1055
#define IDC_FORMID                      1056
#define IDC_SEARCH_COMBO                1057
#define IDC_CASESENSITIVE_CHECK         1060
#define IDC_FIND_LABEL                  1063
#define IDC_WEIGHT                      1070
#define IDC_VALUE                       1073
#define IDC_ENCHANTCHARGE               1080
#define IDC_NAME                        1081
#define IDC_ENCHANTMENT                 1095
#define IDC_EQUIPSLOT                   1096
#define IDC_EDIT_ENCHANTMENT            1103
#define IDC_EDIT_EQUIPSLOT              1104
#define IDC_CNAME                       1113
#define IDC_MODEL                       1113
#define IDC_CREDITS                     1120
#define IDC_DAMAGE                      1120
#define IDC_KEYWORDS                    1124
#define IDC_ITEMNAME                    1125
#define IDC_DNAME                       1126
#define IDC_RESULTCOUNT                 1126
#define IDC_SCHOOLLIST                  1127
#define IDC_COMPONENTCOUNT              1127
#define IDC_TYPELIST                    1128
#define IDC_CONDITION_LIST              1128
#define IDC_REFERENCE_TEXT              1129
#define IDC_BASECOST                    1129
#define IDC_SELECTREFERENCE_BUTTON      1130
#define IDC_REFERENCE_LABEL             1131
#define IDC_SKILLLEVEL                  1131
#define IDC_QUESTITEM                   1132
#define IDC_FUNCTION_TEXT               1132
#define IDC_SELECTENCHANT_BUTTON        1133
#define IDC_SELECTFUNCTION_BUTTON       1133
#define IDC_ADDKEYWORD_BUTTON           1134
#define IDC_FUNCTION_LABEL              1134
#define IDC_EDITKEYWORD_BUTTON          1135
#define IDC_PARAM1_TEXT                 1135
#define IDC_DELKEYWORD_BUTTON           1136
#define IDC_SELECTPARAM1_BUTTON         1136
#define IDC_CONDITION_BUTTON            1137
#define IDC_PARAM1_LABEL                1137
#define IDC_SELECTEQUIPSLOT_BUTTON      1137
#define IDC_PARAM2_TEXT                 1138
#define IDC_SELECTPARAM2_BUTTON         1139
#define IDC_PARAM2_LABEL                1140
#define IDC_VALUE_TEXT                  1141
#define IDC_VALUE_LABEL                 1142
#define IDC_OPERATOR_LIST               1143
#define IDC_OR_CHECK                    1144
#define IDC_RUNTARGET_CHECK             1145
#define IDC_FUNCTION_LIST               1145
#define IDC_USEGLOBAL_CHECK             1146
#define IDC_RESULTITEM                  1146
#define IDC_EDIT_RESULTITEM             1147
#define IDC_SELECTRESULTITEM_BUTTON     1148
#define IDC_COMPONENT_LIST              1149
#define IDC_CRAFTSTATION                1150
#define IDC_TYPEFILTER_STATIC           1150
#define IDC_EDIT_CRAFTSTATION           1151
#define IDC_TYPEFILTER_LIST             1151
#define IDC_SELECTCRAFTSTATION_BUTTON   1152
#define IDC_HOSTILECHECK                1152
#define IDC_COMPONENT                   1153
#define IDC_RECOVERCHECK                1153
#define IDC_EDIT_COMPONENT              1154
#define IDC_DETRIMENTALCHECK            1154
#define IDC_BASEENCHANTMENT             1154
#define IDC_SELECTCOMPONENT_BUTTON      1155
#define IDC_PERCENTMAGCHECK             1155
#define IDC_EDIT_BASEENCHANT            1155
#define IDC_SELECTBASEENCHANT_BUTTON    1156
#define IDC_SELFONLYCHECK               1157
#define IDC_ITEMTYPES                   1157
#define IDC_FXPERSISTCHECK              1158
#define IDC_EDIT_ITEMTYPES              1158
#define IDC_BOUNDCHECK                  1159
#define IDC_SELECTITEMTYPES_BUTTON      1159
#define IDC_SELECT_MODEL                1181
#define IDC_FLICKER                     1190
#define IDC_FLICKERSLOW                 1193
#define IDC_PULSE                       1194
#define IDC_PULSESLOW                   1195
#define IDC_FLICKERNONE                 1196
#define IDS_TT_EDITORID                 15000
#define IDS_TT_FULLNAME                 15001
#define IDS_TT_FORMID                   15002
#define IDS_TT_ARMORTYPE                15003
#define IDS_TT_ARMOR                    15004
#define IDS_TT_VALUE                    15005
#define IDS_TT_WEIGHT                   15006
#define IDS_TT_HEALTH                   15007
#define IDS_TT_ENCHANTMENT              15008
#define IDS_TT_SCRIPT                   15009
#define IDS_TT_PLAYABLE                 15010
#define IDS_TT_HIDERINGS                15011
#define IDS_TT_HIDEAMULET               15012
#define IDS_TT_MALEICON                 15013
#define IDS_TT_FEMALEICON               15014
#define IDS_TT_BIPED                    15015
#define IDS_TT_QUESTITEM                15016
#define IDS_TT_MODEL                    15017
#define IDS_TT_MALEWORLDMODEL           15018
#define IDS_TT_FEMALEWORLDMODEL         15019
#define IDS_TT_MALEBIPEDMODEL           15020
#define IDS_TT_FEMALEBIPEDMODEL         15021
#define IDS_TT_SAVE                     15022
#define IDS_TT_APPLY                    15023
#define IDS_TT_CANCEL                   15024
#define IDS_TT_EDITBIPED                15025
#define IDS_TT_EDITSCRIPT               15026
#define IDS_TT_SELECTSCRIPT             15027
#define IDS_TT_EDITENCHANT              15028
#define IDS_TT_SELECTENCHANT            15029
#define IDS_TT_SOUND                    15030
#define IDS_TT_DANGEROUS                15031
#define IDS_TT_FOODITEM                 15032
#define IDS_TT_AUTOCALC                 15033
#define IDS_TT_DAMAGE                   15034
#define IDS_TT_SPEED                    15035
#define IDS_TT_ENCHANTPOINTS            15036
#define IDS_TT_IGNORERESIST             15037
#define IDS_TT_QUALITY                  15038
#define IDS_TT_APPATYPE                 15039
#define IDS_TT_SCROLL                   15040
#define IDS_TT_NOTAKE                   15041
#define IDS_TT_TEACHES                  15042
#define IDS_TT_CONTRESPAWNS             15043
#define IDS_TT_OPENSOUND                15044
#define IDS_TT_CLOSESOUND               15045
#define IDS_TT_ENCHTYPE                 15046
#define IDS_TT_COST                     15047
#define IDS_TT_CHARGE                   15048
#define IDS_TT_INGREDIENT               15049
#define IDS_TT_SPRING                   15050
#define IDS_TT_SUMMER                   15051
#define IDS_TT_FALL                     15052
#define IDS_TT_WINTER                   15053
#define IDS_TT_CALCEACH                 15054
#define IDS_TT_CALCALL                  15055
#define IDS_TT_CHANCENONE               15056
#define IDS_TT_CREATURETEMPLATE         15057
#define IDS_TT_USEALLSPELLS             15058
#define IDS_TT_SCPTTYPE                 15059
#define IDS_TT_USES                     15060
#define IDS_TT_CAPACITY                 15061
#define IDS_TT_SOUL                     15062
#define IDS_TT_SOUNDFILE                15063
#define IDS_TT_MINATTENUATION           15064
#define IDS_TT_MAXATTENUATION           15065
#define IDS_TT_STATICATTENUATION        15066
#define IDS_TT_FREQADJUSTMENT           15067
#define IDS_TT_STARTTIME                15068
#define IDS_TT_STOPTIME                 15069
#define IDS_TT_RANDOMFREQSHIFT          15070
#define IDS_TT_RANDOMPLAY               15071
#define IDS_TT_RANDOMLOCATION           15072
#define IDS_TT_LOOP                     15073
#define IDS_TT_MENUSOUND                15074
#define IDS_TT_IGNOREENVIRONMENT        15075
#define IDS_TT_2DSOUND                  15076
#define IDS_TT_360LFE                   15077
#define IDS_TT_SPELTYPE                 15078
#define IDS_TT_LEVEL                    15079
#define IDS_TT_IGNORELOS                15080
#define IDS_TT_NOABSORBREFLECT          15081
#define IDS_TT_PCSTARTSPELL             15082
#define IDS_TT_SCRIPTALWAYSAPPLIES      15083
#define IDS_TT_SILENCEIMMUNE            15084
#define IDS_TT_WEAPTYPE                 15085
#define IDS_TT_REACH                    15086
#define IDS_TT_ICON                     15087
#define IDS_TT_SELECTCREATURE           15088
#define IDS_TT_EDITCREATURE             15089
#define IDS_TT_EDITSOUND                15090
#define IDS_TT_SELECTSOUND              15091
#define IDS_TT_EDITINGREDIENT           15092
#define IDS_TT_SELECTINGREDIENT         15093
#define IDS_TT_FADE                     15094
#define IDS_TT_REDCOLOR                 15095
#define IDS_TT_GREENCOLOR               15096
#define IDS_TT_BLUECOLOR                15097
#define IDS_TT_TIME                     15098
#define IDS_TT_OFFBYDEFAULT             15099
#define IDS_TT_FLICKER                  15100
#define IDS_TT_SPOTLIGHT                15101
#define IDS_TT_SPOTSHADOW               15102
#define IDS_TT_DYNAMIC                  15103
#define IDS_TT_NEGATIVE                 15104
#define IDS_TT_COLORBOX                 15105
#define IDS_TT_CARRIED                  15106
#define IDS_TT_FLICKERTYPE              15107
#define IDS_TT_FOV                      15108
#define IDS_TT_FALLOFF                  15109
#define IDS_TT_RADIUS                   15110
#define ID_FILE_IMPORT_CSV              32772
#define ID_FILE_EXPORT_SELECTEDITEMS    32773
#define ID_FILE_EXPORTCSV_SELECTEDITEMS 32774
#define ID_FILE_EXPORTCSV_ALLITEMS      32775
#define ID_FILE_EXPORTCSV_ITEMTYPE      32776
#define ID_FILE_EXPORTCSV_SELECTEDITEMS2 32776
#define ID_RECORDTREE_RELOAD            32777
#define ID_RECORDTREE_EXPORTTOCSV       32778
#define ID_VIEW_FILESTRUCTURE           32779
#define ID_FILE_EXPORT_CSVEXTERIORLOCATIONS 32780
#define ID_FILE_EXPORT_CSVEXTMAPMARKERS 32781
#define ID_HELP_TESTFIELDLOOKUP         32782
#define ID_FILE_EXPORT_CSVEXPORTEXTERIORPLANTS 32783
#define ID_EDIT_FINDBINARYDATA          32784
#define ID_HELP_TESTFINDFORMID          32785
#define ID_EDIT_SELECTALL               32786
#define ID_VIEW_ERROR_BAR               32787
#define ID_TEST_MEMORYSPEED             32788
#define ID_TEST_TOKENSCRIPTS            32789
#define ID_MENU_CLEAN                   32790
#define ID_RECORD_CLEAN                 32791
#define ID_RECORD_MOVEACTIVE            32792
#define ID_MENU_EDITRECORD              32794
#define ID_MENU_NEWRECORD               32795
#define ID_EDIT_NEWRECORD               32796
#define ID_RECORD_TOGGLEDELETE          32797
#define ID_MENU_TOGGLEIGNORE            32798
#define ID_RECORD_TOGGLEIGNORE          32800
#define ID_MENU_TOGGLEQUEST             32801
#define ID_RECORD_TOGGLEQUEST           32802
#define ID_VIEW_UNDOBAR                 32803
#define ID_RECORD_RENAME                32804
#define ID_RECORD_CREATECOPY            32805
#define ID_RECORD_BATCHEDIT             32806
#define ID_LVLOLIST_DELETE              32807
#define ID_LVLLIST_DELETE               32808
#define ID_LVLLIST_ADD                  32809
#define ID_LVLLIST_EDIT                 32810
#define ID_DELETE_ITEM                  -32724
#define ID_ADD_COUNT                    32813
#define ID_MINUS_COUNT                  32814
#define ID_ADD_LEVEL                    32815
#define ID_MINUS_LEVEL                  32816
#define ID_LVL_EDITRECORD               32818
#define ID_LVLLIST_EDITRECORD           32819
#define ID_EFFECTLIST_EDIT              32820
#define ID_EFFECTLIST_ADD               32821
#define ID_EFFECTLIST_DELETE            32822
#define ID_EFFECTLIST_EDITSCRIPT        32824
#define ID_HELP_TESTOUTPUTEFFECTS       32825
#define ID_VIEW_RESOURCEVIEWER          32828
#define ID_HELP_TESTRECORDSIZE          32829
#define ID_HELP_UESPWIKI                32831
#define ID_HELP_CSWIKI                  32832
#define ID_TEST_CLEANRECOMPILEALL       32834
#define ID_TEST_RECOMPILEALL            32835
#define ID_HELP_TESTCOMPARESCRIPTS      32836
#define ID_VIEW_RESETLISTS              32837
#define ID_ROOT_INSERTBEFORE            32838
#define ID_ROOT_INSERTAFTER             32839
#define ID_ROOT_MOVEUP                  32840
#define ID_ROOT_MOVEDOWN                32841
#define ID_ROOT_DELETE                  32842
#define ID_COND_INSERTBEFORE            32843
#define ID_COND_INSERTAFTER             32844
#define ID_COND_MOVEUP                  32845
#define ID_COND_MOVEDOWN                32846
#define ID_COND_DELETE                  32847
#define ID_CONDITION_COPYCONDITON       32848
#define ID_COND_COPYCONDITON            32849
#define ID_COND_COPYCONDITION           32850
#define ID_COMPONENT_ADD                32851
#define ID_COMPONENT_DELETE             32852
#define ID_COMPONENT_EDIT               32853
#define ID_Menu                         32854
#define ID_COMPONENT_INCREASE           32855
#define ID_COMPONENT_DECREASE           32856

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32859
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
