//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by skyedit.rc
//
#define IDS_TT_CNAME                    1
#define IDS_TT_KEYWORDS                 2
#define ID_APPLY_BUTTON                 3
#define ID_CLEAR_BUTTON                 4
#define IDS_TT_DESCRIPTION              5
#define ID_DELETE_BUTTON                6
#define IDCANCEL2                       7
#define ID_CLEAR_FILTER                 8
#define IDS_TT_SCHOOL                   9
#define ID_ADD_BUTTON                   10
#define IDS_TT_EFFECTTYPE               11
#define ID_MOVEUP_BUTTON                12
#define ID_DELETE_BUTTON2               13
#define ID_EDIT_BUTTON                  14
#define ID_MOVEDOWN_BUTTON              15
#define IDS_TT_TYPE                     16
#define ID_DELETE_BUTTON4               17
#define IDD_ABOUTBOX                    100
#define IDD_SREDIT_FORM                 101
#define IDD_ERRORBAR                    102
#define IDC_POINTER_COPY                103
#define IDC_NODROP_CURSOR               104
#define IDD_RACE_BASICPAGE              105
#define IDR_MAINFRAME                   106
#define IDR_SREDITTYPE                  107
#define IDD_LOAD_DLG                    108
#define IDD_PROGRESS_DLG                109
#define IDR_RECORDTREE_MENU             110
#define IDB_FOLDER                      111
#define IDR_RECORDLIST_MENU             112
#define IDD_SRERROR_DLG                 113
#define IDB_FILE                        114
#define IDD_FILETREE_DLG                115
#define IDD_FINDBINARY_DLG              116
#define IDI_ARMOR                       117
#define IDD_SELECTRECORD_DLG            118
#define IDD_PROMPT_DLG                  119
#define IDR_DEFAULT_RECORD_ACCEL        120
#define IDD_UNDOBAR                     121
#define IDD_INPUT_DLG                   122
#define IDD_BATCHEDIT_DLG               123
#define IDD_FIND_DLG                    124
#define IDI_FIND                        125
#define IDR_MAINFRAME1                  126
#define IDR_KEYWORDRECORD_MENU          126
#define IDR_SRVIEWTYPE                  127
#define IDR_LVLITEMLIST_MENU            128
#define IDR_LVLI_ACCELERATOR            129
#define IDR_EFFECTLIST_MENU             130
#define IDR_EFFECT_ACCELERATOR          131
#define IDR_BOOK_MENU                   132
#define IDR_SCRIPT_MENU                 133
#define IDD_RESOURCE_VIEW               134
#define IDD_KEYWORD_VIEW                135
#define IDD_WEAP_VIEW                   136
#define IDD_MGEF_VIEW                   137
#define IDD_FUNCTION_DLG                138
#define IDD_CONDITION_DLG               139
#define IDR_CONDITION_MENU              140
#define IDD_GLOB_VIEW                   141
#define IDD_GMST_VIEW                   142
#define IDR_COMPONENT_MENU              143
#define IDD_COBJ_VIEW                   144
#define IDR_COMPONENT_ACCEL             145
#define IDR_CONTAINERLIST_MENU          146
#define IDD_ENCH_VIEW                   147
#define IDR_LVLITEMLIST_MENU1           148
#define IDR_MGEFSOUNDLIST_MENU          149
#define IDD_SPEL_VIEW                   150
#define IDC_GOODDROP_CURSOR             151
#define IDR_FLSTLIST_MENU               152
#define IDD_AMMO_VIEW                   153
#define IDR_OUTFITLIST_MENU             154
#define IDD_ARMO_VIEW                   155
#define IDD_BODYPARTS_DLG               156
#define IDD_ALCH_VIEW                   157
#define IDD_INGR_VIEW                   158
#define IDD_SCRL_VIEW                   159
#define IDD_BOOK_VIEW                   160
#define IDD_STAT_VIEW                   161
#define IDD_MISC_VIEW                   162
#define IDD_LVLI_VIEW                   163
#define IDD_LVLEDIT_DLG                 164
#define IDD_LVLN_VIEW                   165
#define IDD_LVSP_VIEW                   166
#define IDD_CONT_VIEW                   167
#define IDD_CONTITEMEDIT_DLG            168
#define IDD_LIGH_VIEW                   169
#define IDD_MGEFSNDDEDIT_DLG            170
#define IDD_ACTI_VIEW                   171
#define IDD_ARMA_VIEW                   172
#define IDD_SLGM_VIEW                   173
#define IDD_SHOU_VIEW                   174
#define IDD_WOOP_VIEW                   175
#define IDD_CLAS_VIEW                   176
#define IDD_RAWDATA_DLG                 177
#define IDD_PERK_VIEW                   178
#define IDD_CAMS_VIEW                   179
#define IDD_SOUN_VIEW                   180
#define IDD_BOUNDS_DLGDIALOG1           181
#define IDD_BOUNDS_DLG                  182
#define IDD_SNDR_VIEW                   183
#define IDD_SNCT_VIEW                   185
#define IDD_SOPM_VIEW                   186
#define IDD_SOPMEDIT_DLG                187
#define IDD_OTFT_VIEW                   188
#define IDD_CLFM_VIEW                   189
#define IDD_FLST_VIEW                   190
#define IDD_ECZN_VIEW                   191
#define IDD_RACE_VIEW                   192
#define IDD_RACE_MOVEPAGE               193
#define IDD_RACE_ATTACKPAGE             194
#define IDD_EDITFLAGS_DLG               195
#define IDD_RACE_MODELPAGE              196
#define IDD_RACE_UNKNOWNPAGE            197
#define IDD_RACE_FACEPAGE               198
#define IDD_RACE_HEADPAGE1              199
#define IDD_RACE_TINTPAGE               200
#define IDD_AVIF_VIEW                   201
#define IDD_FUNCTIONPARAM_DLG           202
#define IDR_PERKSECTION_MENU            224
#define IDR_ERRORBAR_MENU               225
#define IDR_RESOURCETREE_MENU           226
#define IDD_SCRIPT_VIEW                 227
#define IDD_SCRIPTERROR_VIEW            229
#define IDR_SCRIPTLIST_MENU             230
#define IDR_SCRIPTTEXT_MENU             232
#define IDR_SCRIPTTEXT_ACCEL            233
#define IDR_ERRORBAR_ACCEL              234
#define IDR_RESOURCE_VIEW               235
#define IDR_SCRIPT_VIEW                 236
#define IDR_SCRIPTRECORD_MENU           237
#define IDD_SCRIPTPROPERTY_DLG          238
#define IDD_NEWSCRIPTPROPERTY_DLG       240
#define IDR_CONDITIONRECORD_MENU        241
#define IDD_NEWSCRIPT_DLG               241
#define IDR_ARMORARMA_MENU              242
#define IDD_SELECTSCRIPT_DLG            242
#define IDI_UPARROW                     244
#define IDC_RECORDTREE                  1000
#define IDC_RESOURCE_TREE               1001
#define IDC_RECORDLIST                  1002
#define IDC_HBAR                        1003
#define IDC_VEDGE                       1004
#define IDC_FILENAME                    1005
#define IDC_FILE_LIST                   1006
#define IDC_FILESIZE                    1007
#define IDC_FILETIME                    1008
#define IDC_FILE_PROGRESS               1009
#define IDC_FILE_LABEL                  1010
#define IDC_PREVIEW_RICHEDIT            1011
#define IDC_FILE_PERCENT                1012
#define IDC_PREVIEW_IMAGE               1013
#define IDC_MESSAGE                     1014
#define IDC_DETAILS                     1015
#define IDC_TREECTRL                    1016
#define IDC_BINARYDATA_TEXT             1017
#define IDC_SETACTIVE                   1018
#define ID_SAVE_BUTTON                  1019
#define ID_CANCEL_BUTTON                1020
#define ID_UNCHECKALL_BUTTON            1021
#define ID_FIND_BUTTON                  1022
#define ID_CHECKALL_BUTTON              1023
#define IDC_PREVIOUS_TEXT               1024
#define IDC_CURRENT_TEXT                1025
#define ID_BUTTON1                      1026
#define IDC_SCRIPTFILTER                1026
#define IDC_FILTER_TEXT                 1027
#define ID_BUTTON2                      1028
#define IDC_PREVIOUS_FORMID             1029
#define ID_BUTTON3                      1030
#define IDC_CURRENT_FORMID              1031
#define IDC_LABEL                       1032
#define IDC_PARTS_LIST                  1033
#define IDC_INPUTTEXT                   1034
#define IDC_FIELD_LIST                  1035
#define IDC_BATCH_EDIT                  1036
#define IDC_FIND_LIST                   1037
#define IDC_EDITORID                    1038
#define IDC_SECTIONINDEX                1039
#define IDC_BINARY_CHECK                1040
#define IDC_SECTIONRANK                 1040
#define IDC_SECTIONVALUE                1041
#define IDC_FORMID                      1042
#define IDC_SEARCH_COMBO                1043
#define IDC_SECTIONVALUE2               1043
#define IDC_CALCULATEALL                1044
#define IDC_LEVEL                       1045
#define IDC_CASESENSITIVE_CHECK         1046
#define IDC_CALCULATEEACH               1047
#define IDC_FINDSCRIPTS_CHECK           1047
#define IDC_FORMID_CHECK                1048
#define IDC_USEALL                      1049
#define IDC_COUNT                       1050
#define IDC_FIND_LABEL                  1051
#define IDC_MINRANK                     1051
#define IDC_CHANCENONE                  1052
#define IDC_CONDITION                   1052
#define IDC_OBJECT_FORMID               1053
#define IDC_ITEM_LIST                   1054
#define IDC_FORMID2                     1055
#define IDC_WEIGHT                      1056
#define IDC_VALUE                       1057
#define IDC_UNKNOWN                     1058
#define IDC_FOV                         1059
#define IDC_RADIUS                      1060
#define IDC_FALLOFF                     1061
#define IDC_UNKNOWN2a                   1062
#define IDC_Y1                          1063
#define IDC_UNKNOWN3                    1064
#define IDC_Z1                          1065
#define IDC_ENCHANTCHARGE               1066
#define IDC_SECTION_ACTORVALUE          1067
#define IDC_Y2                          1068
#define IDC_DATA3                       1069
#define IDC_NAME                        1070
#define IDC_DATA6                       1071
#define IDC_CNAME                       1072
#define IDC_NNAME                       1073
#define IDC_ANAME                       1073
#define IDC_RECHARGE1                   1074
#define IDC_SECTFNAM                    1074
#define IDC_Z2                          1075
#define IDC_SECTXNAM                    1075
#define IDC_DATA9                       1076
#define IDC_SECTYNAM                    1076
#define IDC_NAME2                       1077
#define IDC_SECTINAM                    1077
#define IDC_RECHARGE2                   1078
#define IDC_SECTHNAM                    1078
#define IDC_DATA12                      1079
#define IDC_SECTVNAM                    1079
#define IDC_RECHARGE3                   1080
#define IDC_DATA15                      1081
#define IDC_DATA18                      1082
#define IDC_DATA21                      1083
#define IDC_DATA24                      1084
#define IDC_ENCHANTMENT                 1085
#define IDC_EQUIPSLOT                   1086
#define IDC_IMPACTSET                   1087
#define IDC_BLOODFX                     1088
#define IDC_SOUNDDRAW                   1088
#define IDC_DRAWSOUND                   1089
#define IDC_MENU                        1089
#define IDC_SHEATHSOUND                 1090
#define IDC_SWINGSOUND                  1091
#define IDC_BOUNDSOUND                  1092
#define IDC_EDIT_ENCHANTMENT            1093
#define IDC_EDIT_EQUIPSLOT              1094
#define IDC_EDIT_IMPACTSET              1095
#define IDC_SOUND                       1096
#define IDC_EDIT_SOUNDDRAW              1096
#define IDC_EDIT_BLOODFX                1097
#define IDC_EDIT_MENU                   1097
#define IDC_EDIT_DRAWSOUND              1098
#define IDC_CATEGORY                    1099
#define IDC_EDIT_SHEATHSOUND            1100
#define IDC_OUTPUTMARKER                1101
#define IDC_EDIT_SWINGSOUND             1102
#define IDC_EDIT_BOUNDSOUND             1103
#define IDC_TRAPSOUND                   1104
#define IDC_EDIT_TRAPSOUND              1105
#define IDC_MODEL                       1106
#define IDC_BASEWEAPON                  1107
#define IDC_TINTINDEX                   1107
#define IDC_INVENTORYICON               1107
#define IDC_DESTROYMODEL                1108
#define IDC_TINTTINP                    1108
#define IDC_MESSAGEICON                 1108
#define IDC_EDIT_BASEWEAPON             1109
#define IDC_FLICKERTYPE                 1110
#define IDC_REDSPIN                     1111
#define IDC_CREDITS                     1112
#define IDC_DAMAGE                      1113
#define IDC_GREENSPIN                   1114
#define IDC_BLUESPIN                    1115
#define IDC_KEYWORDS                    1116
#define IDC_ITEMNAME                    1117
#define IDC_ARMAMODELS                  1118
#define IDC_COUNTEREFFECTS              1118
#define IDC_DNAME                       1119
#define IDC_DATATINV                    1119
#define IDC_RESULTCOUNT                 1120
#define IDC_DATATIRS                    1120
#define IDC_MAGNITUDE                   1121
#define IDC_TRANSLATION                 1122
#define IDC_ACTORSKILL1                 1123
#define IDC_SCHOOLLIST                  1124
#define IDC_COMPONENTCOUNT              1125
#define IDC_AREA                        1126
#define IDC_ACTORSKILL2                 1127
#define IDC_TYPELIST                    1128
#define IDC_CONDITION_LIST              1129
#define IDC_DURATION                    1130
#define IDC_ACTORSKILL3                 1131
#define IDC_REFERENCE_TEXT              1132
#define IDC_BASECOST                    1133
#define IDC_CHARGE                      1134
#define IDC_ACTORSKILL4                 1135
#define IDC_SELECTREFERENCE_BUTTON      1136
#define IDC_COST                        1137
#define IDC_EFFECTPLAYRATE              1138
#define IDC_SKILLUSAGEMULT              1138
#define IDC_ACTORSKILL5                 1139
#define IDC_REFERENCE_LABEL             1140
#define IDC_SKILLLEVEL                  1141
#define IDC_DESCRIPTION                 1142
#define IDC_STAFFMOD                    1143
#define IDC_CHARGETIME                  1143
#define IDC_QUESTITEM                   1144
#define IDC_FUNCTION_TEXT               1145
#define IDC_CASTTIME                    1146
#define IDC_ACTORSKILL6                 1147
#define IDC_SELECTENCHANT_BUTTON        1148
#define IDC_SELECTFUNCTION_BUTTON       1149
#define IDC_UNKNOWN2                    1150
#define IDC_SKILLBOOK                   1151
#define IDC_DYNAMIC                     1152
#define IDC_DANGEROUS                   1153
#define IDC_ACTORSKILL7                 1154
#define IDC_ADDKEYWORD_BUTTON           1155
#define IDC_FUNCTION_LABEL              1156
#define IDC_ADDSCRIPT                   1156
#define IDC_CARRIED                     1157
#define IDC_ADD_COUNTEREFFECTS          1157
#define IDC_EDITKEYWORD_BUTTON          1158
#define IDC_PARAM1_TEXT                 1159
#define IDC_EDITPROPERTIESSCRIPT        1159
#define IDC_SPOTSHADOW                  1160
#define IDC_EDIT_COUNTEREFFECTS         1160
#define IDC_DELKEYWORD_BUTTON           1161
#define IDC_SELECTPARAM1_BUTTON         1162
#define IDC_DELSCRIPT                   1162
#define IDC_UNKNOWNFLAG1                1163
#define IDC_EDITSCRIPT                  1163
#define IDC_CONDITION_BUTTON            1164
#define IDC_PARAM1_LABEL                1165
#define IDC_DEL_COUNTEREFFECTS          1165
#define IDC_SELECTEQUIPSLOT_BUTTON      1166
#define IDC_NOTETYPE                    1167
#define IDC_UNKNOWNFLAG2                1168
#define SPELLS                          1169
#define IDC_SPELLS                      1169
#define IDC_PARAM2_TEXT                 1170
#define IDC_EQUIPSLOTS                  1170
#define IDC_PLAYABLE                    1171
#define IDC_PARAM3_TEXT                 1171
#define IDC_SPELLTOME                   1172
#define IDC_UNKNOWNFLAG3                1173
#define IDC_SELECT_IMPACTSET            1174
#define IDC_SECTION_CONDITIONS          1175
#define IDC_SECTION_CONDITIONS1         1175
#define IDC_SELECT_SOUNDDRAW            1175
#define IDC_ADD_SPELL                   1176
#define IDC_SECTION_CONDITIONS2         1176
#define IDC_SELECT_MENU                 1176
#define IDC_SELECTPARAM2_BUTTON         1177
#define IDC_ADD_EQUIPSLOT               1177
#define IDC_SECTION_CONDITIONS3         1177
#define IDC_SELECTPICKUPSOUND_BUTTON    1178
#define IDC_SELECTPARAM3_BUTTON         1178
#define IDC_SELECTSOUND_BUTTON          1179
#define IDC_SELECTVALUE_BUTTON          1179
#define IDC_SELECT_EQUIPSLOT            1179
#define IDC_SELECT_STATICMODEL          1180
#define IDC_SELECT_BLOODFX              1181
#define IDC_PARAM2_LABEL                1182
#define IDC_SELECTARMMODEL_BUTTON       1183
#define IDC_PARAM3_LABEL                1183
#define IDC_SELECTSTATICMODEL_BUTTON    1184
#define IDC_SELECT_DRAWSOUND            1185
#define IDC_ADD_ARMAMODEL               1186
#define IDC_DELKEYWORD_BUTTON2          1187
#define IDC_DEL_SPELL                   1188
#define IDC_VALUE_TEXT                  1189
#define IDC_DEL_EQUIPSLOT               1189
#define IDC_SELECTUSESOUND_BUTTON       1190
#define IDC_PROPERTY_NAME               1190
#define IDC_SELECTSTATICMODEL_BUTTON2   1191
#define IDC_SELECTSPELL_BUTTON          1192
#define IDC_SELECT_SHEATHSOUND          1193
#define IDC_EDIT_ARMAMODEL              1194
#define IDC_VALUE_LABEL                 1195
#define IDC_SELECT_SWINGSOUND           1196
#define IDC_SELECT_WATER                1197
#define IDC_DEL_ARMAMODEL               1198
#define IDC_OPERATOR_LIST               1199
#define IDC_SELECT_BOUNDSOUND           1200
#define IDC_RUNON_LIST                  1200
#define IDC_OR_CHECK                    1201
#define IDC_SELECT_TRAPSOUND            1202
#define IDC_QUESTALIASES_CHECK          1202
#define IDC_RUNTARGET_CHECK             1203
#define IDC_FUNCTION_LIST               1204
#define IDC_SELECT_BASEWEAPON           1205
#define IDC_USEGLOBAL_CHECK             1206
#define IDC_RESULTITEM                  1207
#define IDC_USEPACKDATA_CHECK           1207
#define IDC_EDIT_RESULTITEM             1208
#define IDC_SWAPSUBJECT_CHECK           1208
#define IDC_SELECTRESULTITEM_BUTTON     1209
#define IDC_COMPONENT_LIST              1210
#define IDC_PRKC_LIST                   1211
#define IDC_CRAFTSTATION                1212
#define IDC_TYPEFILTER_STATIC           1213
#define IDC_EDIT_CRAFTSTATION           1214
#define IDC_TYPEFILTER_LIST             1215
#define IDC_SELECTCRAFTSTATION_BUTTON   1216
#define IDC_HOSTILECHECK                1217
#define IDC_COMPONENT                   1218
#define IDC_RECOVERCHECK                1219
#define IDC_EDIT_COMPONENT              1220
#define IDC_DETRIMENTALCHECK            1221
#define IDC_BASEENCHANTMENT             1222
#define IDC_SELECTCOMPONENT_BUTTON      1223
#define IDC_PERCENTMAGCHECK             1224
#define IDC_EDIT_BASEENCHANT            1225
#define IDC_SELECTBASEENCHANT_BUTTON    1226
#define IDC_SELFONLYCHECK               1227
#define IDC_ITEMTYPES                   1228
#define IDC_FXPERSISTCHECK              1229
#define IDC_EDIT_ITEMTYPES              1230
#define IDC_BOUNDCHECK                  1231
#define IDC_SELECTITEMTYPES_BUTTON      1232
#define IDC_EFFECT_LIST                 1233
#define IDC_WARDCHECK                   1234
#define IDC_EFFECTNAME                  1235
#define IDC_UNKNOWNCHECK1               1236
#define IDC_EDIT_EFFECT                 1237
#define IDC_UNKNOWNCHECK2               1238
#define IDC_SELECTEFFECT_BUTTON         1239
#define IDC_UNKNOWNCHECK3               1240
#define IDC_PERK                        1241
#define IDC_EDIT_PERK                   1242
#define IDC_SELECTPERK_BUTTON           1243
#define IDC_UNKNOWNCHECK4               1244
#define IDC_INVENTORYMODEL              1244
#define IDC_SELECTEQUIPSLO_BUTTON       1245
#define IDC_UNKNOWNCHECK5               1246
#define IDC_EDIT_INVENTORYMODEL         1246
#define IDC_SPELLFLAGS                  1247
#define IDC_SELECT_INVENTORYMODEL       1247
#define IDC_UNKNOWNCHECK6               1248
#define IDC_SPELLTYPE                   1249
#define IDC_UNKNOWNCHECK7               1250
#define IDC_CASTTYPE                    1251
#define IDC_AUTOCALC                    1252
#define IDC_DELIVERYTYPE                1252
#define IDC_ACTORVALUE                  1253
#define IDC_EXTENDDURATION              1253
#define IDC_FOOD                        1253
#define IDC_PCSTARTSPELL                1253
#define IDC_CASTANIM                    1254
#define IDC_EFFECTTYPE                  1254
#define IDC_MEDICINE                    1254
#define IDC_REFERENCEPERSIST            1254
#define IDC_AREAIGNORESLOS              1254
#define IDC_TYPEA                       1255
#define IDC_SOUNDVOLUME                 1255
#define IDC_POISON                      1255
#define IDC_IGNORERESISTANCE            1255
#define IDC_UNKNOWNCHECK8               1256
#define IDC_NOABSORBREFLECT             1256
#define IDC_UNKNOWN1                    1257
#define IDC_TYPEB                       1258
#define IDC_ATTACKEVENT                 1258
#define IDC_TARGETTYPE                  1258
#define IDC_DROPSOUND                   1259
#define IDC_TYPEC                       1260
#define IDC_ENCHANTTYPE                 1260
#define IDC_RACE                        1261
#define IDC_UNKNOWN5                    1262
#define IDC_TYPED                       1263
#define IDC_SELECTDROPSOUND_BUTTON      1264
#define IDC_UNKNOWN6                    1265
#define IDC_IGNORERESIST                1266
#define IDC_SELECTRACE_BUTTON           1267
#define IDC_UNKNOWN7                    1268
#define IDC_VANISH                      1269
#define IDC_RATING                      1270
#define IDC_UNKNOWN8                    1271
#define IDC_PROJECTILE                  1272
#define IDC_ARMORTYPE                   1273
#define IDC_UNKNOWNFLAGS1               1274
#define IDC_ONEHAND                     1275
#define IDC_EDIT_PROJECTILE             1276
#define IDC_TEMPLATE                    1277
#define IDC_TWOHAND                     1278
#define IDC_SELECTPROJECTILE_BUTTON     1279
#define IDC_SELECTTEMPLATE_BUTTON       1280
#define IDC_TIME                        1281
#define IDC_UNKNOWN9                    1282
#define IDC_ALTERATION                  1283
#define IDC_SELECT_MODEL                1284
#define IDC_UNKNOWN10                   1285
#define IDC_SELECT_INVENTORYICON        1285
#define IDC_BLOCK                       1286
#define IDC_SELECT_MESSAGEICON          1286
#define IDC_PICKUPSOUND                 1287
#define IDC_UNKNOWN4                    1288
#define IDC_MATERIAL                    1289
#define IDC_STATICMODEL                 1290
#define IDC_DUALCAST                    1291
#define IDC_SELECT_DESTROYMODEL         1292
#define IDC_SMITHING                    1293
#define IDC_SELECTPICKUP_BUTTON         1294
#define IDC_SELECTMATERIAL_BUTTON       1295
#define IDC_USESOUND                    1296
#define IDC_SPELL                       1297
#define IDC_UNKNOWN10a                  1298
#define IDC_HEAVYARMOR                  1299
#define IDC_EDIT_DROPSOUND              1300
#define IDC_SELECT_DUALCAST             1301
#define IDC_UNKNOWN11                   1302
#define IDC_WATER                       1303
#define IDC_LIGHTARMOR                  1304
#define IDC_EDIT_PICKUPSOUND            1305
#define IDC_UNKNOWN12                   1306
#define IDC_PICKPOCKETING               1307
#define IDC_EDIT_RACE                   1308
#define IDC_EDIT_STATICMODEL            1309
#define IDC_EDIT_DUALCAST               1310
#define IDC_SNEAK                       1311
#define IDC_EDIT_TEMPLATE               1312
#define IDC_EDIT_USESOUND               1313
#define IDC_EDIT_SPELL                  1314
#define IDC_EXPLOSION                   1315
#define IDC_ALCHEMY                     1316
#define IDC_EDIT_MATERIAL               1317
#define IDC_SELECT_EXPLOSION            1318
#define IDC_EDIT_WATER                  1319
#define IDC_SPEECHCRAFT                 1320
#define IDC_FLICKER                     1321
#define IDC_IMPACTDATA                  1322
#define IDC_EDIT_EXPLOSION              1323
#define IDC_CONJURATION                 1324
#define IDC_EDIT_IMPACTDATA             1325
#define IDC_ART1                        1326
#define IDC_CASTINGART                  1326
#define IDC_ILLUSION                    1327
#define IDC_SELECTIMPACTDATA_BUTTON     1328
#define IDC_SELECT_ART1                 1329
#define IDC_SELECT_CASTINGART           1329
#define IDC_RESTORATION                 1330
#define IDC_UNKNOWN17                   1331
#define IDC_RACEUNKNOWN17               1332
#define IDC_FLICKERSLOW                 1333
#define IDC_BODYPARTS                   1334
#define IDC_EDIT_ART1                   1335
#define IDC_EDIT_CASTINGART             1335
#define IDC_ENCHANTING                  1336
#define IDC_UNKNOWN18                   1337
#define IDC_RACEUNKNOWN18               1338
#define IDC_PULSE                       1339
#define IDC_ARMMODEL                    1340
#define IDC_POTIONTYPE                  1341
#define IDC_ART2                        1342
#define IDC_HITEFFECTART                1342
#define IDC_PULSESLOW                   1343
#define IDC_EDIT_ARMMODEL               1344
#define IDC_SKILL                       1345
#define IDC_SELECT_ART2                 1346
#define IDC_SELECT_HITEFFECTART         1346
#define IDC_UNKNOWN19                   1347
#define IDC_RACEUNKNOWN19               1348
#define IDC_FLICKERNONE                 1349
#define IDC_SCALE                       1350
#define IDC_EDIT_ART2                   1351
#define IDC_EDIT_HITEFFECTART           1351
#define IDC_UNKNOWN20                   1352
#define IDC_RACEUNKNOWN20               1353
#define IDC_SELECT_MATERIAL             1354
#define IDC_FADE                        1355
#define IDC_ART3                        1356
#define IDC_ENCHANTART                  1356
#define IDC_UNKNOWN21                   1357
#define IDC_RACEUNKNOWN21               1358
#define IDC_GLOBAL                      1359
#define IDC_RED                         1360
#define IDC_SELECT_ART3                 1361
#define IDC_SELECT_ENCHANTART           1361
#define IDC_UNKNOWN22                   1362
#define IDC_RACEUNKNOWN22               1363
#define IDC_EDIT_GLOBAL                 1364
#define IDC_GREEN                       1365
#define IDC_EDIT_ART3                   1366
#define IDC_EDIT_ENCHANTART             1366
#define IDC_UNKNOWN23                   1367
#define IDC_RACEUNKNOWN23               1368
#define IDC_SELECT_GLOBAL               1369
#define IDC_BLUE                        1370
#define IDC_ART4                        1371
#define IDC_EQUIPABILITY                1371
#define IDC_UNKNOWN24                   1372
#define IDC_RACEUNKNOWN24               1373
#define IDC_OPENSOUND                   1374
#define IDC_COLOR                       1375
#define IDC_SELECT_ART4                 1376
#define IDC_SELECT_EQUIPABILITY         1376
#define IDC_UNKNOWN25                   1377
#define IDC_RACEUNKNOWN25               1378
#define IDC_EDIT_OPENSOUND              1379
#define IDC_EDIT_ART4                   1380
#define IDC_EDIT_EQUIPABILITY           1380
#define IDC_UNKNOWN26                   1381
#define IDC_RACEUNKNOWN26               1382
#define IDC_SELECT_OPENSOUND            1383
#define IDC_RACETINL                    1383
#define IDC_EDIT_SOUND                  1384
#define IDC_RACEPNAME                   1384
#define IDC_IMPACTSET1                  1385
#define IDC_RACEUNAME                   1385
#define IDC_CLOSESOUND                  1386
#define IDC_VNAME                       1386
#define IDC_SELECT_IMPACTSET1           1387
#define IDC_EDIT_CATEGORY               1388
#define IDC_EDIT_CLOSESOUND             1389
#define IDC_EDIT_IMPACTSET1             1390
#define IDC_EDIT_OUTPUTMARKER           1391
#define IDC_SELECT_CLOSESOUND           1392
#define IDC_IMPACTSET2                  1393
#define IDC_IMAGESPACEMOD               1393
#define IDC_TYPE                        1394
#define IDC_SOUNDCHARGE                 1394
#define IDC_SELECT_IMPACTSET2           1395
#define IDC_SELECT_IMAGESPACEMOD        1395
#define IDC_NAME8                       1396
#define IDC_SELECT_SOUNDCHARGE          1396
#define IDC_EDIT_IMPACTSET2             1397
#define IDC_EDIT_IMAGESPACEMOD          1397
#define IDC_EDIT_NAME8                  1398
#define IDC_EDIT_SOUNDCHARGE            1398
#define IDC_SHADER1                     1399
#define IDC_HITSHADER                   1399
#define IDC_SELECT_NAME8                1400
#define IDC_SOUNDREADY                  1400
#define IDC_SELECT_SHADER1              1401
#define IDC_SELECT_HITSHADER            1401
#define IDC_RNAME                       1402
#define IDC_SELECT_SOUNDREADY           1402
#define IDC_EDIT_SHADER1                1403
#define IDC_EDIT_HITSHADER              1403
#define IDC_EDIT_RNAME                  1404
#define IDC_EDIT_SOUNDREADY             1404
#define IDC_SHADER2                     1405
#define IDC_ENCHANTSHADER               1405
#define IDC_SELECT_RNAME                1406
#define IDC_SOUNDRELEASE                1406
#define IDC_SELECT_SHADER2              1407
#define IDC_SELECT_ENCHANTSHADER        1407
#define IDC_EDIT_SHADER2                1408
#define IDC_EDIT_ENCHANTSHADER          1408
#define IDC_LIGHT                       1409
#define IDC_SELECT_LIGHT                1410
#define IDC_EDIT_LIGHT                  1411
#define IDC_SECONDSPELL                 1412
#define IDC_EFFECTOBJECT                1412
#define IDC_SELECT_SECONDSPELL          1413
#define IDC_SELECT_EFFECTOBJECT         1413
#define IDC_EDIT_SECONDSPELL            1414
#define IDC_EDIT_EFFECTOBJECT           1414
#define IDC_UNKNOWN13                   1415
#define IDC_SELECT_PROJECTILE           1416
#define IDC_UNKNOWN14                   1417
#define IDC_SELECT_PERK                 1418
#define IDC_UNKNOWN15                   1419
#define IDC_UNKNOWNCHECK9               1420
#define IDC_UNKNOWN16                   1421
#define IDC_EDIT_SOUNDRELEASE           1421
#define IDC_NOAREACHECK                 1422
#define IDC_SOUND_LIST                  1423
#define IDC_SELECT_SOUNDRELEASE         1423
#define IDC_ADDSOUND                    1424
#define IDC_SOUNDCASTLOOP               1424
#define IDC_DELETESOUND                 1425
#define IDC_EDIT_SOUNDCASTLOOP          1425
#define IDC_TYPE_LIST                   1426
#define IDC_SELECT_SOUNDCASTLOOP        1426
#define IDC_AMBIENTSOUND                1427
#define IDC_SOUNDONHIT                  1427
#define IDC_EDIT_AMBIENTSOUND           1428
#define IDC_EDIT_SOUNDONHIT             1428
#define IDC_SELECT_AMBIENTSOUND         1429
#define IDC_SELECT_SOUNDONHIT           1429
#define IDC_KEYWORD                     1430
#define IDC_EDIT_KEYWORD                1431
#define IDC_SELECT_KEYWORD              1432
#define IDC_VERB                        1433
#define IDC_RACE_LIST                   1434
#define IDC_ADD_RACELIST                1435
#define IDC_EDIT_RACELIST               1436
#define IDC_DEL_RACELIST                1437
#define IDC_FOOTSTEPS                   1438
#define IDC_EDIT_FOOTSTEPS              1439
#define IDC_SELECT_FOOTSTEPS            1440
#define IDC_MALETEXTURE                 1441
#define IDC_EDIT_MALETEXTURE            1442
#define IDC_SELECT_MALETEXTURE          1443
#define IDC_FEMALETEXTURE               1444
#define IDC_EDIT_FEMALETEXTURE          1445
#define IDC_SELECT_FEMALETEXTURE        1446
#define IDC_MALE1STTEXTURE              1447
#define IDC_EDIT_MALE1STTEXTURE         1448
#define IDC_SELECT_MALE1STTEXTURE       1449
#define IDC_FEMALE1STTEXTURE            1450
#define IDC_EDIT_FEMALE1STTEXTURE       1451
#define IDC_SELECT_FEMALE1STTEXTURE     1452
#define IDC_SELECT_RACE                 1453
#define IDC_MALEMODEL                   1454
#define IDC_SELECT_MALEMODEL            1455
#define IDC_FEMALEMODEL                 1456
#define IDC_FILLEDGEM                   1457
#define IDC_SELECT_FEMALEMODEL          1458
#define IDC_EDIT_FILLEDGEM              1459
#define IDC_MALE1STMODEL                1460
#define IDC_SELECT_FILLEDGEM            1461
#define IDC_MALEEGTMODEL                1462
#define IDC_SELECT_MALE1STMODEL         1463
#define IDC_CAPACITY                    1464
#define IDC_SELECT_MALEEGTMODEL         1465
#define IDC_FEMALE1STMODEL              1466
#define IDC_CURRENTSOUL                 1467
#define IDC_POWERWORD1                  1468
#define IDC_FEMALEEGTMODEL              1469
#define IDC_SELECT_FEMALE1STMODEL       1470
#define IDC_EDIT_POWERWORD1             1471
#define IDC_SELECT_FEMALEEGTMODEL       1472
#define IDC_SELECT_POWERWORD1           1473
#define IDC_MALEHAVOKMODEL              1474
#define IDC_SPELL1                      1475
#define IDC_TRAINERLEVEL                1476
#define IDC_SELECT_MALEHAVOKMODEL       1477
#define IDC_EDIT_SPELL1                 1478
#define IDC_TRAINERSKILL                1479
#define IDC_FEMALEHAVOKMODEL            1480
#define IDC_SELECT_SPELL1               1481
#define IDC_MARKSMAN                    1482
#define IDC_SELECT_FEMALEHAVOKMODEL     1483
#define IDC_POWERWORD2                  1484
#define IDC_LOCKPICKING                 1485
#define IDC_TEXTCONTROL                 1486
#define IDC_EDIT_POWERWORD2             1487
#define IDC_DESTRUCTION                 1488
#define IDC_VALUETEXT                   1489
#define IDC_SELECT_POWERWORD2           1490
#define IDC_NEXTPERK                    1491
#define IDC_SPELL2                      1492
#define IDC_EDIT_NEXTPERK               1493
#define IDC_EDIT_SPELL2                 1494
#define IDC_SELECT_NEXTPERK             1495
#define IDC_SELECT_SPELL2               1496
#define IDC_PERKDATA_LIST               1497
#define IDC_POWERWORD3                  1498
#define ID_DELETEPERK_BUTTON            1499
#define IDC_EDIT_POWERWORD3             1500
#define ID_ADDPERK_BUTTON               1501
#define IDC_SELECT_POWERWORD3           1502
#define IDC_SECTIONTYPE                 1503
#define IDC_SPELL3                      1504
#define IDC_SECTION_EDITORID            1505
#define IDC_EDIT_SPELL3                 1506
#define IDC_EDIT_SECTIONEDITORID        1507
#define IDC_SELECT_SPELL3               1508
#define IDC_SELECT_SECTIONEDITORID      1509
#define IDC_SECTION_VALUELABEL1         1510
#define IDC_SECTIONEFFECTTYPE           1511
#define IDC_SECTIONAPPLYTYPE            1512
#define IDC_SECTIONFUNCTIONTYPE         1512
#define IDC_SECTIONUNKNOWNTYPE          1513
#define IDC_SECTION_VALUELABEL2         1513
#define IDC_SECTION_EDITORIDLABEL       1514
#define IDC_PRKC_LABEL                  1515
#define IDC_RICHEDIT21                  1516
#define IDC_SCRIPT_TEXT                 1516
#define IDC_ERRORTEXT                   1516
#define IDC_ACTIVECHECK                 1517
#define IDC_FILTERTEXT                  1518
#define IDC_IMAGESPACE                  1519
#define IDC_EDIT_IMAGESPACE             1520
#define IDC_SELECT_IMAGESPACE           1521
#define IDC_X1                          1522
#define IDC_X2                          1523
#define IDC_UNKNOWN3a                   1524
#define IDC_SOUNDFILE                   1525
#define IDC_SELECT_SOUNDFILE            1526
#define IDC_SOUNDREF                    1527
#define IDC_EDIT_SOUNDREF               1528
#define IDC_SELECT_SOUNDREF             1529
#define IDC_BOUNDS                      1530
#define IDC_SOUNDFLAGS                  1531
#define IDC_FNAME                       1532
#define IDC_SELECT_SOUND                1533
#define IDC_SELECT_CATEGORY             1534
#define IDC_SELECT_OUTPUTMARKER         1535
#define IDC_SOUNDFILE_LIST              1536
#define ID_EDIT_SOUNDFILEa              1537
#define ID_EDIT_SOUNDFILE               1538
#define ID_DELETE_SOUNDFILE             1539
#define ID_SELECT_SOUNDFILE             1540
#define IDC_SOUNDPARENT                 1541
#define ID_ADD_SOUNDFILE                1542
#define IDC_EDIT_SOUNDPARENT            1543
#define IDC_SELECT_SOUNDPARENT          1544
#define IDC_CONTENTTYPE                 1545
#define IDC_DATA1                       1546
#define IDC_DATA2                       1547
#define IDC_DATA4                       1548
#define IDC_DATA5                       1549
#define IDC_DATA7                       1550
#define IDC_DATA8                       1551
#define IDC_DATA10                      1552
#define IDC_DATA11                      1553
#define IDC_DATA13                      1554
#define IDC_DATA14                      1555
#define IDC_DATA16                      1556
#define IDC_DATA17                      1557
#define IDC_DATA19                      1558
#define IDC_DATA20                      1559
#define IDC_DATA22                      1560
#define IDC_DATA23                      1561
#define IDC_DATALABEL1                  1562
#define IDC_DATALABEL2                  1563
#define IDC_DATALABEL3                  1564
#define IDC_DATALABEL4                  1565
#define IDC_DATALABEL5                  1566
#define IDC_DATALABEL6                  1567
#define IDC_DATALABEL7                  1568
#define IDC_DATALABEL8                  1569
#define IDC_ANAMDATA_BUTTON             1570
#define IDC_ONAMDATA_BUTTON             1571
#define IDC_RANK                        1572
#define IDC_SNAMDATA_BUTTON             1573
#define IDC_MINLEVEL                    1574
#define IDC_ZONERESET                   1575
#define IDC_ZONEUNKNOWN1                1576
#define IDC_ZONEUNKNOWN2                1577
#define IDC_FACTION                     1578
#define IDC_EDIT_FACTION                1579
#define IDC_SELECT_FACTION              1580
#define IDC_LOCATION                    1581
#define IDC_EDIT_LOCATION               1582
#define IDC_SELECT_LOCATION             1583
#define IDC_TAB_CTRL                    1584
#define IDC_ACTORVALUE1                 1585
#define IDC_ACTORVALUE2                 1586
#define IDC_ACTORVALUE3                 1587
#define IDC_ACTORVALUE4                 1588
#define IDC_ACTORVALUE5                 1589
#define IDC_ACTORVALUE6                 1590
#define IDC_ACTORVALUE7                 1591
#define IDC_RACEFLAGS                   1592
#define IDC_BODYDATA                    1593
#define IDC_FLAGS_LIST                  1594
#define IDC_MALEHEIGHT                  1595
#define IDC_FEMALEHEIGHT                1596
#define IDC_DEFAULTVOICE                1597
#define IDC_EDIT_DEFAULTVOICE           1598
#define IDC_SELECT_DEFAULTVOICE         1599
#define IDC_DEFAULTHAIRCOLOR            1600
#define IDC_EDIT_DEFAULTHAIRCOLOR       1601
#define IDC_SELECT_DEFAULTHAIRCOLOR     1602
#define IDC_DECAPITATEDHEAD             1603
#define IDC_EDIT_DECAPITATEDHEAD        1604
#define IDC_SELECT_DECAPITATEDHEAD      1605
#define IDC_MOVENAMES                   1606
#define IDC_DECAPITATEDHEAD2            1607
#define IDC_WALKMOVE                    1608
#define IDC_EDIT_DECAPITATEDHEAD2       1609
#define IDC_EDIT_WALKMOVE               1610
#define IDC_SELECT_DECAPITATEDHEAD2     1611
#define IDC_SELECT_WALKMOVE             1612
#define IDC_DEFAULTHAIRCOLOR2           1613
#define IDC_RUNMOVE                     1614
#define IDC_EDIT_DEFAULTHAIRCOLOR2      1615
#define IDC_EDIT_RUNMOVE                1616
#define IDC_SELECT_DEFAULTHAIRCOLOR2    1617
#define IDC_SELECT_RUNMOVE              1618
#define IDC_DEFAULTVOICE2               1619
#define IDC_MOVETYPELIST                1620
#define IDC_EDIT_DEFAULTVOICE2          1621
#define IDC_SELECT_DEFAULTVOICE2        1622
#define IDC_SWIMMOVE                    1623
#define IDC_EDIT_SWIMMOVE               1624
#define IDC_SELECT_SWIMMOVE             1625
#define IDC_FLYMOVE                     1626
#define IDC_EDIT_FLYMOVE                1627
#define IDC_SELECT_FLYMOVE              1628
#define IDC_MOVETYPE                    1629
#define IDC_EDIT_MOVETYPE               1630
#define IDC_SELECT_MOVETYPE             1631
#define IDC_SNEAKMOVE                   1632
#define IDC_EDIT_SNEAKMOVE              1633
#define IDC_SELECT_SNEAKMOVE            1634
#define IDC_DELETE_MOVETYPE             1635
#define IDC_ADD_MOVETYPE                1636
#define IDC_RACEUNKNOWN1                1637
#define IDC_RACEUNKNOWN2                1638
#define IDC_RACEUNKNOWN4                1639
#define IDC_RACEUNKNOWN5                1640
#define IDC_RACEUNKNOWN6                1641
#define IDC_RACEUNKNOWN7                1642
#define IDC_RACEUNKNOWN8                1643
#define IDC_RACEUNKNOWN9                1644
#define IDC_RACEUNKNOWN10               1645
#define IDC_RACEUNKNOWN11               1646
#define IDC_RACEUNKNOWN12               1647
#define IDC_RACEUNKNOWN13               1648
#define IDC_RACEUNKNOWN14               1649
#define IDC_RACEUNKNOWN15               1650
#define IDC_RACEUNKNOWN16               1651
#define IDC_ATTACKLIST                  1700
#define IDC_ATTACKKEYWORD               1701
#define IDC_EDIT_ATTACKKEYWORD          1702
#define IDC_SELECT_ATTACKKEYWORD        1703
#define IDC_ADD_ATTACK                  1704
#define IDC_DELETE_ATTACK               1705
#define IDC_BODYNAMELIST                1706
#define IDC_UNEQUIPSLOT                 1707
#define IDC_EDIT_UNEQUIPSLOT            1708
#define IDC_SELECT_UNEQUIPSLOT          1709
#define IDC_FACEKEYS                    1710
#define IDC_ADD_FACEKEY                 1711
#define IDC_EDIT_FACEKEY                1712
#define IDC_DEL_FACEKEY                 1713
#define IDC_FACEWEIGHTS                 1714
#define IDC_ADD_FACEWEIGHT              1715
#define IDC_DELETE_FACEWEIGHT           1716
#define IDC_FEATURESETS                 1717
#define IDC_HEADFEATURE                 1718
#define IDC_EDIT_HEADFEATURE            1719
#define IDC_SELECT_HEADFEATURE          1720
#define IDC_ADD_FEATURESET              1721
#define IDC_EDIT_FEATURESET             1722
#define IDC_DEL_FEATURESET              1723
#define IDC_HAIRCOLORS                  1724
#define IDC_RACEPRESETS                 1725
#define IDC_ADD_RACEPRESET              1726
#define IDC_EDIT_RACEPRESET             1727
#define IDC_DEL_RACEPRESET              1728
#define IDC_ADD_HAIRCOLOR               1729
#define IDC_EDIT_HAIRCOLOR              1730
#define IDC_DEL_HAIRCOLOR               1731
#define IDC_HEADPARTS                   1732
#define IDC_ADD_HEADPART                1733
#define IDC_EDIT_HEADPART               1734
#define IDC_DEL_HEADPART                1735
#define IDC_MPALIST                     1736
#define IDC_ADD_MPA                     1737
#define IDC_DELETE_MPA                  1738
#define IDC_TINTLIST                    1739
#define IDC_ADD_TINT                    1740
#define IDC_DELETE_TINT                 1741
#define IDC_TINTMASK                    1742
#define IDC_SELECT_TINTMASK             1743
#define IDC_TINDCOLOR                   1744
#define IDC_EDIT_TINDCOLOR              1745
#define IDC_SELECT_TINDCOLOR            1746
#define IDC_TINTDATALIST                1747
#define IDC_AVIFDATA_LIST               1747
#define IDC_ADD_TINTDATA                1748
#define ID_ADD_AVIFSECTION              1748
#define IDC_DELETE_TINTDATA             1749
#define ID_DELETE_AVIFSECTION           1749
#define IDC_DATATINC                    1750
#define IDC_SECTPERK                    1750
#define IDC_EDIT_DATATINC               1751
#define IDC_EDIT_SECTPERK               1751
#define IDC_SELECT_DATATINC             1752
#define IDC_SELECT_SECTPERK             1752
#define IDC_SECTSNAM                    1753
#define IDC_EDIT_SECTSNAM               1754
#define IDC_SELECT_SECTSNAM             1755
#define IDC_SECTCNAM                    1756
#define ID_ADD_SECTCNAM                 1757
#define ID_DELETE_SECTCNAM              1758
#define ID_EDIT_SECTCNAM                1759
#define IDC_CONDITION_LABEL             1760
#define IDC_PARAM_LIST                  1761
#define IDC_FILTER_LABEL                1762
#define IDC_SCRIPT_LIST                 1764
#define IDC_LOADSCRIPT                  1766
#define IDC_NEWSCRIPT                   1767
#define IDC_COMPILESCRIPT               1768
#define IDC_SAVESCRIPT                  1769
#define IDC_SAVEASSCRIPT                1770
#define IDC_COMPILESCRIPT2              1771
#define IDC_FIND                        1771
#define IDC_FINDNEXT                    1772
#define IDC_PROPERTYLIST                1774
#define IDC_PROPERTYDATALIST            1775
#define IDC_PROPERTY_VALUE              1780
#define IDC_SELECT_PROPERTYVALUE        1781
#define IDC_VALUE_USEDEFAULT            1782
#define IDC_PROPERTY_VALUE2             1783
#define IDC_SELECT_PROPERTYVALUE2       1784
#define IDC_VALUE1_LABEL                1785
#define IDC_VALUE2_LABEL                1786
#define IDC_PROPERTY_ADD                1787
#define IDC_PROPERTY_DELETE             1788
#define IDC_PROPERTY_DUPLICATE          1789
#define IDC_PROPERTYTYPES               1789
#define IDC_PROPERTY_MOVEUP             1790
#define IDC_PROPERTYNAME                1790
#define IDC_PROPERTY_MOVEDOWN           1791
#define IDC_PROPERTYVALUE               1791
#define IDC_NEW_PROPERTY                1792
#define IDC_HIDDENCHECK                 1792
#define IDC_PROPERTYDOC                 1793
#define IDC_SCRIPTLIST                  1793
#define IDC_ARRAYCHECK                  1794
#define IDC_RESISTLIST                  1794
#define IDC_TAPERCURVE                  1795
#define IDC_TAPERWEIGHT                 1796
#define IDC_TAPERDURATION               1797
#define IDC_CASTINGDELAY                1798
#define IDC_SECONDAVWEIGHT              1799
#define IDC_DUALCASTSCALE               1800
#define IDC_SCRIPTAIDATASCORE           1801
#define IDC_SCRIPTAIDATADELAY           1802
#define IDC_MAGICFLAGS                  1803
#define IDC_DISPELEFFECTS               1804
#define IDC_EFFECTOBJECTLABEL           1805
#define IDC_DESTRUCTDATA                1809
#define IDC_RANGE                       1810
#define IDC_NODUALCASTMODS              1811
#define IDC_CASTDURATION                1812
#define IDC_AUTOCALC1                   1813
#define IDC_SCRIPTALWAYSAPPLIES         1815
#define IDC_AUTOCALC5                   1817
#define IDC_FORCEEXPLODE                1817
#define IDS_TT_EDITORID                 15000
#define IDS_TT_FULLNAME                 15001
#define IDS_TT_FORMID                   15002
#define IDS_TT_ARMORTYPE                15003
#define IDS_TT_ARMOR                    15004
#define IDS_TT_VALUE                    15005
#define IDS_TT_WEIGHT                   15006
#define IDS_TT_HEALTH                   15007
#define IDS_TT_ENCHANTMENT              15008
#define IDS_TT_SCRIPT                   15009
#define IDS_TT_PLAYABLE                 15010
#define IDS_TT_HIDERINGS                15011
#define IDS_TT_HIDEAMULET               15012
#define IDS_TT_MALEICON                 15013
#define IDS_TT_FEMALEICON               15014
#define IDS_TT_BIPED                    15015
#define IDS_TT_QUESTITEM                15016
#define IDS_TT_MODEL                    15017
#define IDS_TT_MALEWORLDMODEL           15018
#define IDS_TT_FEMALEWORLDMODEL         15019
#define IDS_TT_MALEBIPEDMODEL           15020
#define IDS_TT_FEMALEBIPEDMODEL         15021
#define IDS_TT_SAVE                     15022
#define IDS_TT_APPLY                    15023
#define IDS_TT_CANCEL                   15024
#define IDS_TT_EDITBIPED                15025
#define IDS_TT_EDITSCRIPT               15026
#define IDS_TT_SELECTSCRIPT             15027
#define IDS_TT_EDITENCHANT              15028
#define IDS_TT_SELECTENCHANT            15029
#define IDS_TT_SOUND                    15030
#define IDS_TT_DANGEROUS                15031
#define IDS_TT_FOODITEM                 15032
#define IDS_TT_AUTOCALC                 15033
#define IDS_TT_DAMAGE                   15034
#define IDS_TT_SPEED                    15035
#define IDS_TT_ENCHANTPOINTS            15036
#define IDS_TT_IGNORERESIST             15037
#define IDS_TT_QUALITY                  15038
#define IDS_TT_APPATYPE                 15039
#define IDS_TT_SCROLL                   15040
#define IDS_TT_NOTAKE                   15041
#define IDS_TT_TEACHES                  15042
#define IDS_TT_CONTRESPAWNS             15043
#define IDS_TT_OPENSOUND                15044
#define IDS_TT_CLOSESOUND               15045
#define IDS_TT_ENCHTYPE                 15046
#define IDS_TT_COST                     15047
#define IDS_TT_CHARGE                   15048
#define IDS_TT_INGREDIENT               15049
#define IDS_TT_SPRING                   15050
#define IDS_TT_SUMMER                   15051
#define IDS_TT_FALL                     15052
#define IDS_TT_WINTER                   15053
#define IDS_TT_CALCEACH                 15054
#define IDS_TT_CALCALL                  15055
#define IDS_TT_CHANCENONE               15056
#define IDS_TT_CREATURETEMPLATE         15057
#define IDS_TT_USEALLSPELLS             15058
#define IDS_TT_SCPTTYPE                 15059
#define IDS_TT_USES                     15060
#define IDS_TT_CAPACITY                 15061
#define IDS_TT_SOUL                     15062
#define IDS_TT_SOUNDFILE                15063
#define IDS_TT_MINATTENUATION           15064
#define IDS_TT_MAXATTENUATION           15065
#define IDS_TT_STATICATTENUATION        15066
#define IDS_TT_FREQADJUSTMENT           15067
#define IDS_TT_STARTTIME                15068
#define IDS_TT_STOPTIME                 15069
#define IDS_TT_RANDOMFREQSHIFT          15070
#define IDS_TT_RANDOMPLAY               15071
#define IDS_TT_RANDOMLOCATION           15072
#define IDS_TT_LOOP                     15073
#define IDS_TT_MENUSOUND                15074
#define IDS_TT_IGNOREENVIRONMENT        15075
#define IDS_TT_2DSOUND                  15076
#define IDS_TT_360LFE                   15077
#define IDS_TT_SPELTYPE                 15078
#define IDS_TT_LEVEL                    15079
#define IDS_TT_IGNORELOS                15080
#define IDS_TT_NOABSORBREFLECT          15081
#define IDS_TT_PCSTARTSPELL             15082
#define IDS_TT_SCRIPTALWAYSAPPLIES      15083
#define IDS_TT_SILENCEIMMUNE            15084
#define IDS_TT_WEAPTYPE                 15085
#define IDS_TT_REACH                    15086
#define IDS_TT_ICON                     15087
#define IDS_TT_SELECTCREATURE           15088
#define IDS_TT_EDITCREATURE             15089
#define IDS_TT_EDITSOUND                15090
#define IDS_TT_SELECTSOUND              15091
#define IDS_TT_EDITINGREDIENT           15092
#define IDS_TT_SELECTINGREDIENT         15093
#define IDS_TT_FADE                     15094
#define IDS_TT_REDCOLOR                 15095
#define IDS_TT_GREENCOLOR               15096
#define IDS_TT_BLUECOLOR                15097
#define IDS_TT_TIME                     15098
#define IDS_TT_OFFBYDEFAULT             15099
#define IDS_TT_FLICKER                  15100
#define IDS_TT_SPOTLIGHT                15101
#define IDS_TT_SPOTSHADOW               15102
#define IDS_TT_DYNAMIC                  15103
#define IDS_TT_NEGATIVE                 15104
#define IDS_TT_COLORBOX                 15105
#define IDS_TT_CARRIED                  15106
#define IDS_TT_FLICKERTYPE              15107
#define IDS_TT_FOV                      15108
#define IDS_TT_FALLOFF                  15109
#define IDS_TT_RADIUS                   15110
#define ID_FILE_IMPORT_CSV              32772
#define ID_FILE_EXPORT_SELECTEDITEMS    32773
#define ID_FILE_EXPORTCSV_SELECTEDITEMS 32774
#define ID_FILE_EXPORTCSV_ALLITEMS      32775
#define ID_FILE_EXPORTCSV_ITEMTYPE      32776
#define ID_FILE_EXPORTCSV_SELECTEDITEMS2 32776
#define ID_RECORDTREE_RELOAD            32777
#define ID_RECORDTREE_EXPORTTOCSV       32778
#define ID_VIEW_FILESTRUCTURE           32779
#define ID_FILE_EXPORT_CSVEXTERIORLOCATIONS 32780
#define ID_FILE_EXPORT_CSVEXTMAPMARKERS 32781
#define ID_HELP_TESTFIELDLOOKUP         32782
#define ID_FILE_EXPORT_CSVEXPORTEXTERIORPLANTS 32783
#define ID_EDIT_FINDBINARYDATA          32784
#define ID_HELP_TESTFINDFORMID          32785
#define ID_EDIT_SELECTALL               32786
#define ID_VIEW_ERROR_BAR               32787
#define ID_TEST_MEMORYSPEED             32788
#define ID_TEST_TOKENSCRIPTS            32789
#define ID_MENU_CLEAN                   32790
#define ID_RECORD_CLEAN                 32791
#define ID_RECORD_MOVEACTIVE            32792
#define ID_MENU_EDITRECORD              32794
#define ID_MENU_NEWRECORD               32795
#define ID_EDIT_NEWRECORD               32796
#define ID_RECORD_TOGGLEDELETE          32797
#define ID_MENU_TOGGLEIGNORE            32798
#define ID_RECORD_TOGGLEIGNORE          32800
#define ID_MENU_TOGGLEQUEST             32801
#define ID_RECORD_TOGGLEQUEST           32802
#define ID_VIEW_UNDOBAR                 32803
#define ID_RECORD_RENAME                32804
#define ID_RECORD_CREATECOPY            32805
#define ID_RECORD_BATCHEDIT             32806
#define ID_LVLOLIST_DELETE              32807
#define ID_LVLLIST_DELETE               32808
#define ID_LVLLIST_ADD                  32809
#define ID_LVLLIST_EDIT                 32810
#define ID_DELETE_ITEM                  -32724
#define ID_ADD_COUNT                    32813
#define ID_MINUS_COUNT                  32814
#define ID_ADD_LEVEL                    32815
#define ID_MINUS_LEVEL                  32816
#define ID_LVL_EDITRECORD               32818
#define ID_LVLLIST_EDITRECORD           32819
#define ID_EFFECTLIST_EDIT              32820
#define ID_EFFECTLIST_ADD               32821
#define ID_EFFECTLIST_DELETE            32822
#define ID_EFFECTLIST_EDITSCRIPT        32824
#define ID_HELP_TESTOUTPUTEFFECTS       32825
#define ID_VIEW_RESOURCEVIEWER          32828
#define ID_HELP_TESTRECORDSIZE          32829
#define ID_HELP_UESPWIKI                32831
#define ID_HELP_CSWIKI                  32832
#define ID_TEST_CLEANRECOMPILEALL       32834
#define ID_TEST_RECOMPILEALL            32835
#define ID_HELP_TESTCOMPARESCRIPTS      32836
#define ID_VIEW_RESETLISTS              32837
#define ID_ROOT_INSERTBEFORE            32838
#define ID_ROOT_INSERTAFTER             32839
#define ID_ROOT_MOVEUP                  32840
#define ID_ROOT_MOVEDOWN                32841
#define ID_ROOT_DELETE                  32842
#define ID_COND_INSERTBEFORE            32843
#define ID_COND_INSERTAFTER             32844
#define ID_COND_MOVEUP                  32845
#define ID_COND_MOVEDOWN                32846
#define ID_COND_DELETE                  32847
#define ID_CONDITION_COPYCONDITON       32848
#define ID_COND_COPYCONDITON            32849
#define ID_COND_COPYCONDITION           32850
#define ID_COMPONENT_ADD                32851
#define ID_COMPONENT_DELETE             32852
#define ID_COMPONENT_EDIT               32853
#define ID_Menu                         32854
#define ID_COMPONENT_INCREASE           32855
#define ID_COMPONENT_DECREASE           32856
#define ID_SNDDLIST_DELETE              32861
#define ID_SNDDLIST_EDIT                32862
#define ID_SNDDLIST_ADD                 32863
#define ID_SNDDLIST_EDITRECORD          32864
#define ID_MENU_VIEWDATADATA            32865
#define ID_MENU_VIEWRAWDATA             32866
#define ID_HELP_TESTOUTPUTPERKS         32867
#define ID_EDIT_USELOCALSTRINGS         32868
#define ID_EDIT_SETMODAUTHOR            32869
#define ID_EDIT_SETMODDESCRIPTION       32870
#define ID_MENU_VIEWSUMMARY             32871
#define ID_OUTFITLIST_ADD               32872
#define ID_OUTFITLIST_EDIT              32873
#define ID_OUTFITLIST_DELETE            32874
#define ID_MENU_EDITRECORD32875         32875
#define ID_MENU_EDITBASERECORD          32876
#define ID_OUTFITLIST_EDITBASE          32877
#define ID_FLSTLIST_ADD                 32878
#define ID_FLSTLIST_EDIT                32879
#define ID_FLSTLIST_DELETE              32880
#define ID_FLSTTLIST_EDITBASE           32881
#define ID_PERKSECTION_ADD              32882
#define ID_PERKSECTION_DELETE           32883
#define ID_PERKSECTION_DUPLICATE        32884
#define ID_PERKSECTION_EDIT             32885
#define ID_ERRORBAR_COPY                32886
#define ID_CONDITION_PASTECONDITION     32887
#define ID_CONDITION_DUPLICATE          32888
#define ID_RESOURCEMENU_EDIT            32889
#define ID_RESOURCEMENU_EDITEXTERNAL    32890
#define ID_VIEW_RESOURCESCRIPTS         32892
#define ID_SCRIPTLISTMENU_NEWSCRIPT     32893
#define ID_SCRIPTLISTMENU_LOADSCRIPT    32894
#define ID_SCRIPTLISTMENU_DELETE        32895
#define ID_SCRIPTLISTMENU_COMPILE       32896
#define ID_SCRIPT_NEWSCRIPT             32897
#define ID_SCRIPT_LOADSCRIPT            32898
#define ID_SCRIPT_DELETE                32899
#define ID_SCRIPT_COMPILE               32900
#define ID_SCRIPT_LOAD                  32901
#define ID_SCRIP_NEW                    32902
#define ID_SCRIPT_NEW                   32903
#define ID_SCRIPT_REMOTE                32904
#define ID_SCRIPT_REMOVE                32905
#define ID_SCRIPTLISTMENU_SAVE          32906
#define ID_SCRIPTLISTMENU_SAVEAS        32907
#define ID_SCRIP_SAVEAS                 32908
#define ID_SCRIP_SAVE                   32909
#define ID_SCRIPT_SAVE                  32910
#define ID_SCRIPT_SAVEAS                32911
#define ID_SCRIPTTEXTMENU_UNDO          32912
#define ID_SCRIPTTEXTMENU_CUT           32913
#define ID_SCRIPTTEXTMENU_COPY          32914
#define ID_SCRIPTTEXTMENU_PASTE         32915
#define ID_SCRIPTTEXTACC_COPY           32923
#define ID_SCRIPTTEXTACC_CUT            32924
#define ID_SCRIPTTEXTACC_PASTE          32925
#define ID_SCRIPTTEXTACC_UNDO           32927
#define ID_ERROR_COPY                   32928
#define ID_SCRIPTRECORD_ADD             32934
#define ID_SCRIPTRECORD_EDITPROPERTIES  32935
#define ID_SCRIPTRECORD_EDITSCRIPT      32936
#define ID_SCRIPTRECORD_REMOVE          32937
#define ID_SCRIPTRECORD_DELETE          32938
#define ID_SCRIPTRECORD_ADDNEW          32939
#define ID_SCRIPTLISTMENU_TESTTOKENS    32940
#define ID_SCRIPTLISTMENU_TESTPROPERTIES 32941
#define ID_SCRIPTRECORD_COPYSCRIPTS     32942
#define ID_SCRIPTRECORD_PASTESCRIPTS    32943
#define ID_CONDITIONRECORD_COPYCONDITIONS 32944
#define ID_CONDITIONRECORD_PASTECONDITIONS 32945
#define ID_CONDITIONRECORD_COPY         32946
#define ID_CONDITIONRECORD_PASTE        32947
#define ID_CONDITIONRECORD_DELETEALL    32948
#define ID_ARMAMENU_ADD                 32949
#define ID_ARMAMENU_EDIT                32950
#define ID_ARMAMENU_DELETE              32951
#define ID_ARMAMENU_EDITBASE            32952
#define ID_KEYWORD_ADD                  32953
#define ID_KEYWORD_EDIT                 32954
#define ID_KEYWORD_EDITBASE             32955
#define ID_KEYWORD_DELETE               32956
#define ID_VIEW_ACTIVEONLY              32957
#define ID_MENU_CHANGEMODINDEX          32960
#define ID_MENU_CHANGEFORMID            32961
#define ID_MENU_ASSIGNNEWFORMID         32962
#define ID_SCRIPTTEXTMENU_FIND          32963
#define ID_SCRIPTTEXTMENU_FINDNEXT      32965
#define ID_SCRIPTTEXTMENU_SELECTALL     32966

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32968
#define _APS_NEXT_CONTROL_VALUE         1814
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
